# <div align="center"><span style="color:Purple">**<i> NumPy Practice</i>**</span> </div>

#### <span style="color:Blue">**Part 1: 1-6**</span> 
#### <span style="color:Blue">**Part 2: 7-12**</span> 
#### <span style="color:Blue">**Part 3: 13-16**</span> 
####  <span style="color:Blue">**Part 4: 17-20**</span> 

## <span style="color:Brown">**Part 1: Array Creation and Properties**</span> 

####  1.Create a 1D array named arr1d with integers from 0 to 9.

In [1]:
import numpy as np 

In [2]:
arr_1d = np.arange(10)
arr_1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 2.Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [3]:
arr_2d = np.ones((3, 3))
arr_2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 3.Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [4]:
random_matrix = np.random.randn(3, 3)
random_matrix

array([[-0.47121804,  1.74238779, -0.15699396],
       [ 0.02688645,  0.03920101, -0.74346255],
       [ 1.15376674, -0.75419811,  0.67429346]])

#### 4.Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [5]:
even_numbers = np.arange(10, 51, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 5.Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [6]:
linspace_array  = np.linspace(0, 1, 7)
linspace_array 

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

#### 6.Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
arr.dtype

dtype('int64')

In [9]:
arr.ndim

2

In [10]:
arr.shape

(2, 3)

##  <span style="color:Brown">**Part 2: Array Manipulation**</span>

### 7.Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

##arr_1d = np.arange(10)
reshaped_arr = arr.reshape(2,5)
reshaped_arr

In [11]:
arr = np.arange(1,11)
print("Original array:", arr)

reshape_arr = arr.reshape((2,5))
print("\nReshaped Array:\n", reshape_arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10]

Reshaped Array:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### 8.Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [12]:
reshape_arr.T
print("transposed_arr:\n", reshape_arr.T)

transposed_arr:
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]


transposed_arr = reshape_arr.T

### 9.Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [13]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6]) 

v_stack = np.vstack((a, b))
print("Vertical Stack:\n", v_stack)

Vertical Stack:
 [[1 2 3]
 [4 5 6]]


### 10.Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [14]:
m1 = np.array([[1, 2], [3, 4]]) 
m2 = np.array([[5, 6], [7, 8]])


h_stack = np.hstack((a, b))
print("Horizontal Stack:\n", h_stack)

Horizontal Stack:
 [1 2 3 4 5 6]


### 11.Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [15]:
arr_to_split = np.arange(16).reshape(4, 4) 
h_split = np.hsplit(arr_to_split, 2)
print("Horizontal Split by 4:\n")

for part in h_split:
    print(part)
    print("---")


Horizontal Split by 4:

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
---
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
---


### 12.Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [16]:
arr_to_split = np.arange(16).reshape(4, 4) 
v_split = np.vsplit(arr_to_split, 2)
print("Vertical Split by 2:\n", v_split[0], "\n---\n", v_split[1])

Vertical Split by 2:
 [[0 1 2 3]
 [4 5 6 7]] 
---
 [[ 8  9 10 11]
 [12 13 14 15]]


##  <span style="color:Brown">**Part 3: Indexing, Slicing, and Boolean Indexing**</span>

### 13.Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [17]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
data [1,2]

np.int64(15)

### 14.From the data array (from Q13), extract the first two rows and all columns.

In [18]:
data [0:2, :]

array([[10, 11, 12],
       [13, 14, 15]])

### 15.From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [19]:
data[[0,1,2],[1,2,1]]

array([11, 15, 17])

### 16.Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [20]:
scores = np.array([85, 92, 78, 65, 95, 88])
#print("Max scores:", np.max(scores>80))
High_scores = scores[scores>80]
print("Highest scores:", High_scores)

Highest scores: [85 92 95 88]


##  <span style="color:Brown">**Part 4: Numerical Operations and Aggregations**</span>

### 17.Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [21]:
arr_op1 = np.array([10, 20, 30]) 
arr_op2 = np.array([2, 4, 6])

print("\nArray 1:", arr_op1)
print("\nArray 2:", arr_op2)

print("---")

print("Multiplication:",  arr_op1 * arr_op2)
print("Division:",  arr_op1 / arr_op2)



Array 1: [10 20 30]

Array 2: [2 4 6]
---
Multiplication: [ 20  80 180]
Division: [5. 5. 5.]


### 18.Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [22]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix.sum()

np.int64(45)

### 19.From the matrix (from Q18), calculate the mean of each column.


In [23]:
column_means = np.mean(matrix, axis=0)
print("Mean of each column:", column_means)

Mean of each column: [4. 5. 6.]


### 20.Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [24]:
price_array = np.array([100, 150, 200, 250]) 
discount_percentage = 0.10
Discounted_prices = price_array * (1 - discount_percentage)
print("Discounted prices:", Discounted_prices)

Discounted prices: [ 90. 135. 180. 225.]
