# <div align="center"><span style="color:DarkGreen">**<i>Numpy Task 2: Smart building</i>**</span> </div>


#### Scenario: You are a data scientist monitoring environmental conditions in a smart building. You have collected sensor data (temperature, humidity, pressure) over 24 hours, with readings taken every minute. Your goal is to process this raw data to find key statistics and identify anomalies.

## <span style="color:DarkBlue">**1.Data Generation:**</span>

###  <span style="color:LightBlue">1.1 Create a NumPy array for time_in_minutes from 0 to 1439 (24 hours * 60 minutes).</span>

In [57]:
import numpy as np

In [58]:
time_in_minutes = np.arange(24 * 60)
time_in_minutes

array([   0,    1,    2, ..., 1437, 1438, 1439], shape=(1440,))

###  <span style="color:LightBlue">1.2 Generate synthetic temperature data: a base temperature (e.g., 22°C) with some random fluctuations (use np.random.normal).</span>

In [59]:
#Use the random.normal() method to get a Normal Data Distribution.
#It has three parameters:
# 1: loc - (Mean) where the peak of the bell exists. it means the center of the normal distribution
# 2: scale - (Standard Deviation) how flat the graph distribution should be. the spread
# 3: size - The shape of the returned array. It means how many random values to generate 
# for the size it will be 1440 (24h*60m/h)
temperature_data = np.random.normal(loc = 22 , scale= 1 , size= 1440 )
temperature_data

array([22.06124059, 22.55836318, 21.84920534, ..., 22.0772695 ,
       22.32784242, 22.16189607], shape=(1440,))

### <span style="color:LightBlue">1.3 Generate synthetic humidity data: a base humidity (e.g., 55%) with random fluctuations, ensuring values stay realistic (0-100%).</span>

In [60]:
humidity_data = np.random.normal(loc = 55 , scale= 5 , size= 1440 )
#using  Clip (limit) the values in an array.
humidity_data = np.clip(humidity_data, 0, 100)
humidity_data

array([57.42219297, 58.1147192 , 54.54725725, ..., 53.17286202,
       56.41358684, 43.04176707], shape=(1440,))

### <span style="color:LightBlue">1.4 Generate synthetic pressure data: a base pressure (e.g., 1012 hPa) with random fluctuations.</span>

In [61]:
pressure_data =  np.random.normal(loc = 1012, scale = 5, size = 1440)
pressure_data                                

array([1019.64398466, 1010.92435844, 1018.443599  , ..., 1018.44560674,
       1009.30702592, 1008.55567369], shape=(1440,))

### <span style="color:LightBlue">1.5 Combine these into a single 2D NumPy array where each row represents a minute and columns are [time, temperature, humidity, pressure].</span>

In [62]:
#Stack 1-D arrays as columns into a 2-D array.
#Take a sequence of 1-D arrays and stack them as columns to make a single 2-D array. 2-D arrays are stacked as-is, 
#just like with hstack. 1-D arrays are turned into 2-D columns first.

data_array = np.column_stack((time_in_minutes,temperature_data,humidity_data,pressure_data))
data_array

array([[0.00000000e+00, 2.20612406e+01, 5.74221930e+01, 1.01964398e+03],
       [1.00000000e+00, 2.25583632e+01, 5.81147192e+01, 1.01092436e+03],
       [2.00000000e+00, 2.18492053e+01, 5.45472572e+01, 1.01844360e+03],
       ...,
       [1.43700000e+03, 2.20772695e+01, 5.31728620e+01, 1.01844561e+03],
       [1.43800000e+03, 2.23278424e+01, 5.64135868e+01, 1.00930703e+03],
       [1.43900000e+03, 2.21618961e+01, 4.30417671e+01, 1.00855567e+03]],
      shape=(1440, 4))

## <span style="color:DarkBlue">2. Basic Statistics:</span> 
 

### <span style="color:LightBlue">2.1 Calculate the average, minimum, maximum temperature, humidity, and pressure for the entire 24-hour period.</span>

In [63]:
average_temperature_data = np.mean(temperature_data)
average_temperature_data

np.float64(22.040688987353693)

In [64]:
maximum_temperature_data = np.max(temperature_data)
maximum_temperature_data

np.float64(26.257340759608795)

In [65]:
minimum_temperature_data = np.min(temperature_data)
minimum_temperature_data

np.float64(19.245216732852256)

In [66]:
average_humidity_data = np.mean(humidity_data)
average_humidity_data

np.float64(55.002928174614965)

In [67]:
maximum_humidity_data = np.max(humidity_data)
maximum_humidity_data

np.float64(77.45100579050971)

In [68]:
minimum_humidity_data = np.min(humidity_data)
minimum_humidity_data

np.float64(37.66873922874507)

In [69]:
average_pressure_data= np.mean(pressure_data)
average_pressure_data

np.float64(1011.9829058090261)

In [70]:
maximum_pressure_data= np.max(pressure_data)
maximum_pressure_data

np.float64(1025.6002837265253)

In [71]:
minimum_pressure_data = np.min(pressure_data)
minimum_pressure_data

np.float64(996.335582352869)

### <span style="color:LightBlue">2.2 Find the standard deviation for each of these parameters.</span>

In [72]:
np.std(temperature_data)

np.float64(1.0094337685757524)

In [73]:
np.std(humidity_data)

np.float64(5.124830871720933)

In [74]:
np.std(pressure_data)

np.float64(4.890897384386921)

## <span style="color:DarkBlue">3. Hourly Averages:</span>  

### <span style="color:LightBlue">3.1 Reshape the data (or use slicing/aggregation) to calculate the average temperature, humidity, and pressure for each hour of the day. You should end up with 24 average values for each parameter.</span>

In [94]:
temperature_data = data_array[:, 1].reshape(24, 60)
temperature_data

array([[22.06124059, 22.55836318, 21.84920534, ..., 20.62005494,
        21.57170516, 21.82483564],
       [22.67432776, 23.36331451, 23.88723115, ..., 21.960566  ,
        22.81501389, 24.55617997],
       [24.90818974, 22.42450465, 22.33559665, ..., 22.03341655,
        21.48267554, 21.7966677 ],
       ...,
       [22.73529833, 22.87598714, 20.49024986, ..., 22.7630698 ,
        20.72647415, 22.04627414],
       [21.22089167, 22.43602781, 22.97374716, ..., 21.73735909,
        20.8585077 , 21.5967092 ],
       [23.08527979, 21.37504571, 20.98182927, ..., 22.0772695 ,
        22.32784242, 22.16189607]], shape=(24, 60))

In [101]:
temperature_data_avg = data_array.mean(axis=1)
temperature_data_avg

array([274.78185455, 273.14936021, 274.2100154 , ..., 632.67393457,
       631.51211379, 628.18983421], shape=(1440,))

In [103]:
humidity_data = data_array[:, 2].reshape(24, 60)
humidity_data

array([[57.42219297, 58.1147192 , 54.54725725, ..., 61.37267473,
        55.96691344, 66.31726873],
       [60.80353925, 57.04246708, 56.21955302, ..., 51.96582677,
        56.22906461, 61.01154391],
       [47.75125955, 63.08015821, 53.73880308, ..., 52.29559676,
        57.94404743, 56.98528423],
       ...,
       [60.76510717, 52.12226876, 52.73922729, ..., 54.43296192,
        67.69203021, 55.72608009],
       [50.83983608, 58.62224708, 52.46548473, ..., 59.45297827,
        59.98036634, 53.00834439],
       [52.14640244, 55.44478112, 61.62165444, ..., 53.17286202,
        56.41358684, 43.04176707]], shape=(24, 60))

In [104]:
humidity_data_avg = data_array.mean(axis=1)
humidity_data_avg

array([274.78185455, 273.14936021, 274.2100154 , ..., 632.67393457,
       631.51211379, 628.18983421], shape=(1440,))

In [105]:
pressure_data = data_array[:, 3].reshape(24, 60)
pressure_data

array([[1019.64398466, 1010.92435844, 1018.443599  , ..., 1004.14661706,
        1010.70507856,  999.85964581],
       [1011.11415645, 1009.50768607, 1011.85331265, ..., 1011.41432561,
        1011.15382103, 1017.91844584],
       [1016.10816191, 1014.38022896, 1010.95925141, ..., 1001.15983952,
        1008.21924377, 1014.47288287],
       ...,
       [1020.98237654, 1019.74659283, 1014.52019234, ..., 1018.78969734,
        1004.78299731, 1007.92999544],
       [1011.14515587, 1016.44545336, 1015.1298881 , ..., 1015.34045212,
        1012.86976884, 1008.65683135],
       [1008.53031834, 1005.79656181, 1015.51762641, ..., 1018.44560674,
        1009.30702592, 1008.55567369]], shape=(24, 60))

In [106]:
pressure_data_avg = data_array.mean(axis=1)
pressure_data_avg

array([274.78185455, 273.14936021, 274.2100154 , ..., 632.67393457,
       631.51211379, 628.18983421], shape=(1440,))

## <span style="color:DarkBlue">4. Anomaly Detection (Simple): </span>

### <span style="color:LightBlue">4.1 Identify and count how many minutes the temperature exceeded a certain threshold (e.g., 25°C).</span>

In [84]:
mask=temperature_data[time_in_minutes>25]
mask

array([21.24837418, 20.64880761, 24.5091905 , ..., 22.0772695 ,
       22.32784242, 22.16189607], shape=(1414,))

### <span style="color:LightBlue">4.2 Find the time (in minutes) when the minimum temperature occurred.</span>

In [85]:
mask=temperature_data[time_in_minutes<25]
mask

array([22.06124059, 22.55836318, 21.84920534, 22.43196075, 22.69098086,
       23.74662077, 21.1586212 , 23.29884576, 22.63667812, 21.90796755,
       23.5483926 , 20.81639139, 23.6436077 , 22.63187622, 23.28879409,
       20.32042739, 21.23812572, 23.43664162, 22.76418519, 23.1515669 ,
       22.40731619, 22.66908527, 22.58782345, 21.53734954, 21.77238232])