In [1]:
import numpy as np

In [2]:
arr1d = np.arange(10)
print("arr1d:", arr1d)

arr1d: [0 1 2 3 4 5 6 7 8 9]


In [3]:
arr2d = np.ones((3, 3))
print("arr2d:\n", arr2d)


arr2d:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [4]:
random_matrix = np.random.randn(3, 3)
print("random_matrix:\n", random_matrix)


random_matrix:
 [[-1.0870257  -0.03018487 -0.29601334]
 [ 0.56361406 -0.24590564  0.71168185]
 [-0.79469906  0.13478494  0.76223643]]


In [5]:
even_numbers = np.arange(10, 51, 2)
print("even_numbers:", even_numbers)


even_numbers: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


In [6]:
linspace_array = np.linspace(0, 1, 7)
print("linspace_array:", linspace_array)


linspace_array: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Number of dimensions:", arr.ndim)
print("Data type:", arr.dtype)


Shape: (2, 3)
Number of dimensions: 2
Data type: int64


In [8]:
reshaped_arr = arr1d.reshape(2, 5)
print("reshaped_arr:\n", reshaped_arr)


reshaped_arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
transposed_arr = reshaped_arr.T
print("transposed_arr:\n", transposed_arr)


transposed_arr:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [10]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_v = np.vstack((a, b))
print("Vertical stack:\n", stacked_v)


Vertical stack:
 [[1 2 3]
 [4 5 6]]


In [11]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
stacked_h = np.hstack((m1, m2))
print("Horizontal stack:\n", stacked_h)


Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [12]:
arr_to_split = np.arange(16).reshape(4, 4)
split_h1, split_h2 = np.hsplit(arr_to_split, 2)
print("Horizontal split - Part 1:\n", split_h1)
print("Horizontal split - Part 2:\n", split_h2)


Horizontal split - Part 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Horizontal split - Part 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [13]:
split_v1, split_v2 = np.vsplit(arr_to_split, 2)
print("Vertical split - Part 1:\n", split_v1)
print("Vertical split - Part 2:\n", split_v2)


Vertical split - Part 1:
 [[0 1 2 3]
 [4 5 6 7]]
Vertical split - Part 2:
 [[ 8  9 10 11]
 [12 13 14 15]]


In [14]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
element = data[1, 2]
print("Element at (1,2):", element)


Element at (1,2): 15


In [15]:
slice_rows = data[:2, :]
print("First two rows:\n", slice_rows)


First two rows:
 [[10 11 12]
 [13 14 15]]


In [16]:
fancy = data[[0, 1, 2], [1, 2, 1]]
print("Fancy indexing result:", fancy)



Fancy indexing result: [11 15 17]


In [17]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print("Scores > 80:", high_scores)


Scores > 80: [85 92 95 88]


In [18]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])

product = arr_op1 * arr_op2
division = arr_op1 / arr_op2

print("Element-wise multiplication:", product)
print("Element-wise division:", division)


Element-wise multiplication: [ 20  80 180]
Element-wise division: [5. 5. 5.]


In [19]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
total_sum = matrix.sum()
print("Sum of all elements:", total_sum)


Sum of all elements: 45


In [20]:
column_means = matrix.mean(axis=0)
print("Column means:", column_means)


Column means: [4. 5. 6.]


In [21]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discounted_prices = price_array * (1 - discount_percentage)
print("Discounted prices:", discounted_prices)


Discounted prices: [ 90. 135. 180. 225.]
