In [3]:
import numpy as np

**Part 1: Array Creation and Properties**

**Q1: Create a 1D array named arr1d with integers from 0 to 9.**

In [4]:
arr1d=np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Q2: Create a 2D array named arr2d with shape (3, 3) filled with ones.**

In [5]:
arr2d=np.ones((3, 3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Q3: Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.**

In [6]:
random_matrix=np.random.randn(3, 3)
random_matrix

array([[-0.26217662, -1.06391908, -0.51656554],
       [ 1.23242078, -0.13996773, -0.36621691],
       [ 0.78136572, -0.77840791,  1.38791456]])

**Q4: Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).**

In [7]:
even_numbers = np.arange(10,51,2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Q5: Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).**

In [8]:
landspace_array= np.linspace(0,1,7)
landspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

**Q6: Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype?**

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape,arr.ndim, arr.dtype

((2, 3), 2, dtype('int64'))

**Part 2: Array Manipulation**

**Q1:Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.**

In [10]:
reshape_arr1d =arr1d.reshape(2,5)
reshape_arr1d

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**Q2:Transpose reshaped_arr (from Q7). Name the result transposed_arr.**

In [11]:
transpose_arr1d=reshape_arr1d.T
transpose_arr1d

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

**Q3:Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.**

In [14]:
a=np.array([1,2,3])
b=np.array([4,5,6])
vertical_stack=np.vstack((a,b))
vertical_stack

array([[1, 2, 3],
       [4, 5, 6]])

**Q4:Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.**

In [15]:
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
horizontal_stack=np.hstack((m1,m2))
horizontal_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**Q5:Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.**

In [18]:
arr_to_split=np.arange(16).reshape(4,4)
split_horizontally=np.hsplit(arr_to_split,2)
split_horizontally [0]
split_horizontally[1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

**Q6:Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.**

In [42]:
split_vertically=np.vsplit(arr_to_split,2)
split_vertically[0]
split_vertically[1]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

**Part 3: Indexing, Slicing, and Boolean Indexing**

**Q1:Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.**

In [43]:
data=np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
element=data[1,2]
element

np.int64(15)

**Q2:From the data array (from Q13), extract the first two rows and all columns.**

In [44]:
row_0_1=data[:2, :]
row_0_1

array([[10, 11, 12],
       [13, 14, 15]])

**Q3:From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).**

In [45]:
fancy_index=data[[0,1,2],[1,2,1]]
fancy_index

array([11, 15, 17])

**Q4:Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.**

In [46]:
scores=np.array([85,92,78,65,95,88])
scores_greater_than_80=scores[scores>80]
scores_greater_than_80 

array([85, 92, 95, 88])

**Part 4: Numerical Operations and Aggregations**

**Q1:Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).**

In [47]:
arr_op1=np.array([10,20,30])
arr_op2=np.array([2,4,6])
product=arr_op1 * arr_op2
division= arr_op1/arr_op2
print("\nThe product = ",product)
print("\nThe Division =", division)


The product =  [ 20  80 180]

The Division = [5. 5. 5.]


**Q2:Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.**

In [48]:
matrix=np.array([[1,2,3],[4,5,6],[7,8,9]])
summation =np.sum(matrix)
summation

np.int64(45)

**Q3:From the matrix (from Q18), calculate the mean of each column.**

In [49]:
column_mean=np.mean(matrix, axis=0)
column_mean

array([4., 5., 6.])

**Q4:Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.**

In [50]:
price_array=np.array([100,150,200,250])
discount_percentage=0.10
discounted_prices=price_array*(1-discount_percentage)
discounted_prices

array([ 90., 135., 180., 225.])