**Part 1: Array Creation and Properties**

In [111]:
arr1d = np.arange(0,10) #ends with 10 but not including it
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Create a 2D array named arr2d with shape (3, 3) filled with ones.**

In [112]:
arr2d = np.ones((3,3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.**

In [113]:
random_matrix = np.random.randn(3,3)
random_matrix

array([[ 2.21389059e+00,  4.83620651e-01, -1.09231254e+00],
       [ 6.67934123e-01, -6.21396689e-01,  4.72711252e-01],
       [-2.65983939e-01,  3.86354399e-01, -7.18997099e-04]])

**Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).**

even_numbers = np.arange(10,51,2)
even_numbers

**Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).**

In [114]:
linspace_array = np.linspace(0,1,7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

**Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.**

In [115]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
type(arr)

numpy.ndarray

In [116]:
arr.ndim

2

In [117]:
arr.shape

(2, 3)

**Part 2: Array Manipulation**

**1.Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr**

In [118]:
reshaped_arr = arr1d.reshape(2,5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**2.Transpose reshaped_arr (from Q7). Name the result transposed_arr.**

In [119]:
transposed_arr = reshaped_arr.T
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

**3.Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.**

In [120]:
a= np.array([1,2,3])
b= np.array([4,5,6])
vertically_stack = np.vstack((a,b))
vertically_stack

array([[1, 2, 3],
       [4, 5, 6]])

**4.Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.**

In [121]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]]) 
horizontally_stack= np.hstack((m1,m2))
horizontally_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**5.Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.**

In [122]:
arr_to_split = np.arange(16).reshape(4, 4)
arr_to_split = np.hsplit(arr_to_split,2)
print("horizantally split by 2:\n", arr_to_split[0], "\n",
      "horizantally split by 2:\n",arr_to_split[1])

horizantally split by 2:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
 horizantally split by 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


**6.Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.**

In [123]:
arr_to_split = np.arange(16).reshape(4, 4)
arr_to_split

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [124]:
first_two_rows = arr_to_split[:2, :]
# Last two rows
last_two_rows = arr_to_split[2:, :]
print("first two rows" , first_two_rows)
print("\n")
print("last two rows" , last_two_rows)

first two rows [[0 1 2 3]
 [4 5 6 7]]


last two rows [[ 8  9 10 11]
 [12 13 14 15]]


**Part 3: Indexing, Slicing, and Boolean Indexing**

**1.Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.**

In [125]:
data= np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
data
first_row_second_column = data[1:2, 2:]
first_row_second_column 

array([[15]])

**2.From the data array (from Q13), extract the first two rows and all columns.**

In [130]:
data= np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
data


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [131]:
two_rows_all_column = data[0:2, 0:3]
two_rows_all_column 

array([[10, 11, 12],
       [13, 14, 15]])

**3.From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).**

In [138]:
elements = data[[0, 1, 2], [1, 2, 1]]
print(elements)


[11 15 17]


**4.Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.**

In [141]:
scores = np.array([85, 92, 78, 65, 95, 88])
print("orignal scores: ",scores)

condition= scores >80
filtered_data= scores[condition]
print("filtered_data: " , filtered_data)

orignal scores:  [85 92 78 65 95 88]
filtered_data:  [85 92 95 88]


**Part 4: Numerical Operations and Aggregations**

**1.Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).**

In [146]:
arr_op1 = np.array([10,20,30])
arr_op2 = np.array([2,4,6])
print("multiplication(arr_op1 * arr_op2) :" ,arr_op1*arr_op2)
print("division(arr_op1/arr_op2):", arr_op1/arr_op2)

multiplication(arr_op1 * arr_op2) : [ 20  80 180]
division(arr_op1/arr_op2): [5. 5. 5.]


**2.Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.**

In [148]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("sum of all elements = " , np.sum(matrix))

sum of all elements =  45


**3.From the matrix (from Q18), calculate the mean of each column.**

In [149]:
print("mean of each element in the columns: " , np.mean(matrix , axis=0))

mean of each element in the columns:  [4. 5. 6.]


**4.Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.**

In [152]:
price_array = np.array([100, 150, 200, 250]) 
discount_percentage = 0.10
discount= price_array * discount_percentage
after_discount= price_array - discount
print("price after discount : " , after_discount)

price after discount :  [ 90. 135. 180. 225.]
