In [45]:
import numpy as np

* Part 1: Array Creation and Properties

In [4]:
# 1. Create a 1D array named arr1d with integers from 0 to 9
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
# 2. Create a 2D array named arr2d with shape (3, 3) filled with ones
arr2d = np.ones((3, 3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
# 3. Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution
random_matrix = np.random.randn(3, 3)
random_matrix

array([[ 0.92372346, -0.10369396,  0.0107386 ],
       [-0.35112279, -0.06543734, -0.86971573],
       [-0.39367867, -0.44511328,  1.69185442]])

In [7]:
# 4. Create an array named even_numbers containing even numbers from 10 to 50 (inclusive)
even_numbers = np.arange(10, 51, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [8]:
# 5. Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive)
linspace_array = np.linspace(0, 1, 7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [14]:
# 6. Given arr = np.array([[1, 2, 3], [4, 5, 6]]), print its shape, ndim, and dtype
arr = np.array([[1, 2, 3], [4, 5, 6]])
type(arr)

numpy.ndarray

* Part 2: Array Manipulation

In [30]:
# Q7: Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

arr1d= arr1d.reshape(2, 5)
print("arr1d_1:\n",arr1d )

arr1d_1:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [31]:
# Q8: Transpose reshaped_arr (from Q7). Name the result transposed_arr.
arr1d.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [32]:
#Q9: Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v_stack  = np.vstack((a, b))
print("vertical_stack :\n", v_stack )

vertical_stack :
 [[1 2 3]
 [4 5 6]]


In [35]:
# Q10:Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
H_stack  = np.hstack((m1, m2))
print("Horizontally stacked arrays:\n", H_stack ) 

Horizontally stacked arrays:
 [[1 2 5 6]
 [3 4 7 8]]


* Q5: Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [41]:
#Q11: Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.
arr_to_split = np.arange(16).reshape(4, 4)
print("Original Array:\n", arr_to_split)

h_split = np.hsplit(arr_to_split, 2)
print("Horizental Split by 2:\n", h_split[0], "\n---\n", h_split[1])

Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizental Split by 2:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
---
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [39]:
#Q12 Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.
v_split = np.vsplit(arr_to_split, 2)
print("Vertical Split by 2:\n", v_split[0], "\n---\n", v_split[1])

Vertical Split by 2:
 [[0 1 2 3]
 [4 5 6 7]] 
---
 [[ 8  9 10 11]
 [12 13 14 15]]


* Part 3: Indexing, Slicing, and Boolean Indexing

In [51]:
#Q13 Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
element = data[1, 2]
element

np.int64(15)

In [58]:
#Q14 From the data array (from Q13), extract the first two rows and all columns.
#arr [:2, :]
subset = data[:2, :]
subset

array([[10, 11, 12],
       [13, 14, 15]])

In [59]:
#Q15 From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).
elements = data[[0, 1, 2], [1, 2, 1]]
elements

array([11, 15, 17])

* selfnote Q15
###### 11 → row 0, column 1
###### 15 → row 1, column 2
###### 17 → row 2, column 1

##### Q16 Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.
* nparray = np.array([85, 92, 78, 65, 95, 88])
* indices = np.where(nparray > 80)
* filtered = nparray[indices]
* print("Values > 80:", filtered)
* if it was a condition

In [68]:
#Q16

scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print("higherscores:", high_scores)

higherscores: [85 92 95 88]


* Part 4: Numerical Operations and Aggregations

In [70]:
#Q17 Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).
 
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
print("Multiplication (arr1 * arr2):" , arr_op1 * arr_op2)
print("Division (arr1 / arr2):" ,  arr_op1 / arr_op2)

Multiplication (arr1 * arr2): [ 20  80 180]
Division (arr1 / arr2): [5. 5. 5.]


In [71]:
#Q18: Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print ("sum:", np.sum(matrix))

sum: 45


In [76]:
#Q19 From the matrix (from Q18), calculate the mean of each column.

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_mean = matrix.mean(axis=0)
column_mean

array([4., 5., 6.])

In [73]:
#Q20 Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discounted = price_array * (1 - discount_percentage)
print("after discount:", discounted)

after discount: [ 90. 135. 180. 225.]
