# NumPy Practice

In [1]:
import numpy as np

### Part 1: Array Creation and Properties

## 1.Create a 1D array named arr1d with integers from 0 to 9.

In [4]:
arr1d = np.arange(10)
print("1D arry:", arr1d)

1D arry: [0 1 2 3 4 5 6 7 8 9]


## 2.Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [9]:
arr2d = np.ones((3,3))
print("2D arry \n:" , arr2d)

2D arry 
: [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 3.Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [13]:
random_matrix = np.random.randn(3,3)
print("Random 3x3 matrix:\n", random_matrix)

Random 3x3 matrix:
 [[-1.1295745  -0.63445021  0.82962969]
 [ 1.41629745  1.28520507 -0.11250297]
 [-1.49403728  1.20052284  0.18661534]]


## 4.Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [17]:
even_number = np.arange(10,51,2)
print("Even number: ", even_number)

Even number:  [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


## 5.Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [22]:
linspace_array = np.linspace(0,1,7)
print(linspace_array)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


## 6.Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [23]:
Given_arr = np.array([[1,2,3],[4,5,6]])
print("shape", Given_arr.shape)
print("ndim", Given_arr.ndim)
print("type", Given_arr.dtype)

shape (2, 3)
ndim 2
type int64


## Part 2: Array Manipulation

### 1.Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [25]:
Reshape_arr1d = arr1d.reshape(2, 5)
print("Reshaped arry\n", Reshape_arr1d)

Reshaped arry
 [[0 1 2 3 4]
 [5 6 7 8 9]]


## 2.Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [27]:
transpose = Reshape_arr1d.T
print("Transpose\n", transpose)

Transpose
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


## 3.Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stack_1D_arry= np.vstack((a,b))
print("stacked 1d arry\n: ", stack_1D_arry)

stacked 1d arry
:  [[1 2 3]
 [4 5 6]]


## 4. Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [31]:
e= ([[1, 2], [3, 4]])
r= ([[5, 6], [7, 8]]) 
stack_2d_arry = np.hstack((e,r))
print("Stack two 2D array\n:", stack_2d_arry)

Stack two 2D array
: [[1 2 5 6]
 [3 4 7 8]]


## 5.Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [32]:
arr_to_split = np.arange(16).reshape(4, 4)
print("Original array:\n", arr_to_split)


left_part = arr_to_split[:, :2]   
right_part = arr_to_split[:, 2:]  

print("\nLeft part:\n", left_part)
print("\nRight part:\n", right_part)


Original array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Left part:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

Right part:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


## 6.Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [33]:
arr_to_split = np.arange(16).reshape(4, 4)

part1, part2 = np.vsplit(arr_to_split, [2])

print("First part:")
print(part1)

print("\nSecond part:")
print(part2)


First part:
[[0 1 2 3]
 [4 5 6 7]]

Second part:
[[ 8  9 10 11]
 [12 13 14 15]]


# Part 3: Indexing, Slicing, and Boolean Indexing

## 1.Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [34]:
data = np.array([[10, 11, 12], 
                 [13, 14, 15], 
                 [16, 17, 18]])

element = data[1, 2]
print(element)


15


## 2.From the data array (from Q13), extract the first two rows and all columns.

In [35]:
first_two_rows = data[:2, :]
print(first_two_rows)


[[10 11 12]
 [13 14 15]]


## 3.From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [36]:
rows = np.array([0, 1, 2])
cols = np.array([1, 2, 1])

elements = data[rows, cols]
print(elements)


[11 15 17]


## 5. Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [37]:
scores = np.array([85, 92, 78, 65, 95, 88])

filtered_scores = scores[scores > 80]
print(filtered_scores)


[85 92 95 88]


## Part 4: Numerical Operations and Aggregations

## 1.Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [38]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])

multiplication = arr_op1 * arr_op2
division = arr_op1 / arr_op2

print("Element wise multiplication:", multiplication)
print("Element wise division:", division)


Element wise multiplication: [ 20  80 180]
Element wise division: [5. 5. 5.]


## 2.Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [39]:
matrix = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

total_sum = np.sum(matrix)
print("Sum of all elements:", total_sum)


Sum of all elements: 45


## 3.From the matrix (from Q18), calculate the mean of each column.

In [40]:
column_means = np.mean(matrix, axis=0)
print("Mean of each column:", column_means)


Mean of each column: [4. 5. 6.]


## 4. Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [41]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10

discounted_prices = price_array * (1 - discount_percentage)
print("Discounted prices:", discounted_prices)


Discounted prices: [ 90. 135. 180. 225.]
