# Smart Building Task
##### Scenario: You are a data scientist monitoring environmental conditions in a smart building. You have collected sensor data (temperature, humidity, pressure) over 24 hours, with readings taken every minute. Your goal is to process this raw data to find key statistics and identify anomalies.

In [20]:
import numpy as np

# Part1: Data Generation: 
#### Create:
##### Array for time_in_minutes-> 0 to 1439.
##### Random temperature data->22°C.
##### Random humidity data->55% -stay realistic  0-100%.
##### Pressure data->1012.
##### Finally, mereging all array. 

In [58]:
time_in_minutes = np.arange(1440)

temperature = np.random.normal(loc=22, scale=1.5, size=1440)
print("temperature", temperature)

humidity = np.random.normal(loc=55, scale=5, size=1440)
humidity = np.clip(humidity, 0, 100)

pressure = np.random.normal(loc=1012, scale=2, size=1440)


sensor_data = np.column_stack((time_in_minutes, temperature, humidity, pressure))

print(sensor_data[:5])

temperature [19.25631112 21.40040653 22.38672703 ... 20.76244856 22.56704846
 22.70076751]
[[0.00000000e+00 1.92563111e+01 5.70520970e+01 1.01300569e+03]
 [1.00000000e+00 2.14004065e+01 5.12623759e+01 1.01006767e+03]
 [2.00000000e+00 2.23867270e+01 5.53755863e+01 1.01247075e+03]
 [3.00000000e+00 2.17986338e+01 4.72153748e+01 1.01464117e+03]
 [4.00000000e+00 2.15609763e+01 5.91003512e+01 1.01539721e+03]]


# Paret 2: Basic Statistics
#### Count minimum, maximum and standerd deviation For each:
##### 1-temperature. 
##### 2-humidity.
##### 3-pressure

In [38]:


temperature_average = np.mean(temperature)
temperature_min = np.min(temperature)
temperature_max = np.max(temperature)
temperature_std = np.std(temperature)


humidity_average = np.mean(humidity)
humidity_min = np.min(humidity)
humidity_max = np.max(humidity)
humidity_std =  np.std(humidity)


pressure_average = np.mean(pressure)
pressure_min = np.min(pressure)
pressure_max = np.max(pressure)
pressure_std = np.std(pressure)



print("Temperature Stats:")
print(f"  Mean: {temperature_average:.2f}")
print(f"  Min: {temperature_min:.2f}")
print(f"  Max: {temperature_max:.2f}")
print(f"  Std: {temperature_std:.2f}")

print("\nHumidity Stats:")
print(f"  Mean: {humidity_average:.2f}")
print(f"  Min: {humidity_min:.2f}")
print(f"  Max: {humidity_max:.2f}")
print(f"  Std: {humidity_std:.2f}")

print("\nPressure Stats:")
print(f"  Mean: {pressure_average:.2f}")
print(f"  Min: {pressure_min:.2f}")
print(f"  Max: {pressure_max:.2f}")
print(f"  Std: {pressure_std:.2f}")


Temperature Stats:
  Mean: 22.02
  Min: 19.03
  Max: 25.30
  Std: 0.98

Humidity Stats:
  Mean: 55.02
  Min: 36.88
  Max: 69.84
  Std: 4.96

Pressure Stats:
  Mean: 1011.96
  Min: 1005.23
  Max: 1018.97
  Std: 1.96


# part4: Anomaly Detection (Simple):
#### Identify and count how many minutes the temperature > 25c.

In [60]:
temperature_exceeded = temperature > 25
temperature_25 = temperature[temperature_exceeded]
high_temp_count = np.sum(temperature_exceeded)
print(f"The temperature greater than 25:", temperature_25 )
print("The minutes of tepmerature that's exceeded: ", high_temp_count)

min_temp_index = np.argmin(temperature)        
min_temp_time = time_in_minutes[min_temp_index] 
min_temp_value = temperature[min_temp_index]
print(f"Minimum temperature occurred at minute: {min_temp_time} (Value: {min_temp_value:.2f}°C)")

The temperature greater than 25: [25.67958087 26.26756501 25.25776422 25.37972311 26.45501298 25.11130585
 25.26892231 25.1158593  26.22275706 25.98003854 26.19463145 25.3177794
 25.3045526  25.24318949 25.36063156 26.05293801 25.09995267 25.51118713
 26.62125387 25.01614304 25.58842267 25.06594273 25.46354119 25.17825966
 25.36205106 27.19561128 25.2187932  25.64534736 25.68270675 25.63873194
 25.28667593 25.42372986 25.46565687 25.30546875 25.10819655]
The minutes of tepmerature that's exceeded:  35
Minimum temperature occurred at minute: 855 (Value: 16.74°C)
