### Part 1: Array Creation and Properties

#### 1- Create a 1D array named arr1d with integers from 0 to 9.

In [4]:
import numpy as np
arr1d = np.arange(0, 10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 2- Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [5]:
arr2d = np.ones((3,3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 3- Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [6]:
random_matrix = np.random.randn(3,3)
random_matrix

array([[-1.36827248, -1.46041714,  0.65820777],
       [ 2.18388093, -0.76186471, -0.32102701],
       [-1.00076513, -0.90388185,  1.18058375]])

#### 4- Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [7]:
even_numbers  = np.arange(10, 51, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 5- Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [8]:
linspace_array = np.linspace(0, 1, 7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

#### 6- Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr = np.shape
arr

<function shape at 0x0000026E6315F7B0>

In [10]:
arr = np.ndim
arr

<function ndim at 0x0000026E63169B30>

In [11]:
arr = np.dtype
arr

numpy.dtype

### Part 2: Array Manipulation

#### 1- Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [12]:
arr1d = arr1d.reshape((2,5))
print("\nReshape Array:\n", arr1d)


Reshape Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


#### 2- Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [13]:
arr1d.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

#### 3- Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [14]:
a = np.array([1, 2, 3]) 
b = np.array([4, 5, 6])

v_stack = np.vstack((a, b))
print("Vertical Stack:\n", v_stack)


Vertical Stack:
 [[1 2 3]
 [4 5 6]]


#### 4- Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [15]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

h_stack = np.hstack((m1, m2))
print("Horizental Stack:\n", h_stack)

Horizental Stack:
 [[1 2 5 6]
 [3 4 7 8]]


#### 5- Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [16]:
arr_to_split = np.arange(16).reshape(4, 4)
print("Original Array:\n", arr_to_split)

h_split = np.hsplit(arr_to_split, 2)
print("Horizental Split by 2:\n", h_split[0], "\n---\n", h_split[1])   

Original Array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Horizental Split by 2:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]] 
---
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


#### 6- Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [17]:
v_split = np.vsplit(arr_to_split, 2)
print("Vertical Split by 2:\n", v_split[0], "\n---\n", v_split[1]) 

Vertical Split by 2:
 [[0 1 2 3]
 [4 5 6 7]] 
---
 [[ 8  9 10 11]
 [12 13 14 15]]


### Part 3: Indexing, Slicing, and Boolean Indexing

#### 1- Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [18]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
element = data[1, 2]
print(element)

15


#### 2- From the data array (from Q13), extract the first two rows and all columns.

In [19]:
arr = data[0:2, :]
arr

array([[10, 11, 12],
       [13, 14, 15]])

#### 3- From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [37]:
rows = [0, 1, 2]
cols = [1, 2, 1]

elements = data[rows, cols]
elements

array([11, 15, 17])

#### 4- Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [21]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print("Scores greater than 80:", high_scores)

Scores greater than 80: [85 92 95 88]


### Part 4: Numerical Operations and Aggregations

#### 1- Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [28]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])

multiplication = arr_op1 * arr_op2
division = arr_op1 / arr_op2
print("The result of Multiplication:", multiplication)
print("The result of Division", division)

The result of Multiplication: [ 20  80 180]
The result of Division [5. 5. 5.]


#### 2- Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [29]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

matrix_sum = np.sum(matrix)
matrix_sum 

np.int64(45)

#### 3- From the matrix (from Q18), calculate the mean of each column.

In [34]:
means = np.mean(matrix, axis=0)
means

array([4., 5., 6.])

#### 4- Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [31]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10

discounted_prices = price_array * (1 - discount_percentage)
print("Discounted prices:", discounted_prices)

Discounted prices: [ 90. 135. 180. 225.]
