### Sales Data Simulation and Analysis
* You are a junior data analyst at an online retail company. Your manager wants to understand daily sales patterns. You need to simulate a month's worth of sales data and then use NumPy to extract insights about sales performance.

In [2]:
import numpy as np
np.random.seed(42)

##### 1- Sales Data Generation: 
###### Simulate daily sales_revenue for 30 days. Assume a base daily revenue (e.g., $1000) with random fluctuations. Use np.random.rand() or np.random.normal() to add variability. Ensure no negative sales.

In [4]:
base_revenue = 1000
sales_revenue = np.random.normal(loc=base_revenue, scale=200, size=30)
sales_revenue = np.clip(sales_revenue, a_min=0, a_max=None)  
sales_revenue

array([ 879.65867755, 1370.4556369 ,  997.30055505,  788.45781421,
       1164.50898242,  755.83127001, 1041.772719  ,  608.06597522,
        734.36279022, 1039.37224717, 1147.693316  , 1034.27365624,
        976.87034352,  939.77926088,  704.29560193,  856.03115832,
        907.87224581, 1211.42444524, 1068.72365791,  647.39196893,
       1064.81679388,  922.98354392,  864.61559994, 1122.33525777,
       1206.1999045 , 1186.25602382,  832.15649536,  938.15752483,
       1066.25268628, 1195.10902542])

###### Simulate units_sold for the same 30 days, correlated with sales revenue but with its own random fluctuations.

In [6]:
average_unit_price= 22
noise = np.random.normal(loc=0, scale=5, size=30)
units_sold = (sales_revenue / average_unit_price) + noise
units_sold = np.clip(units_sold, a_min=0, a_max=None).astype(int)  # Ensure no negative units
units_sold

array([40, 67, 41, 34, 50, 27, 48, 28, 33, 46, 45, 44, 42, 38, 31, 40, 50,
       55, 49, 29, 38, 41, 39, 63, 53, 55, 37, 36, 54, 58])

###### Create two 1D NumPy arrays, one for sales_revenue and one for units_sold.

In [9]:
sales_revenue = np.array(sales_revenue)
units_sold = np.array(units_sold)

print("The Sales Revenue is:", sales_revenue)
print("The Units Sold is:", units_sold)

The Sales Revenue is: [ 879.65867755 1370.4556369   997.30055505  788.45781421 1164.50898242
  755.83127001 1041.772719    608.06597522  734.36279022 1039.37224717
 1147.693316   1034.27365624  976.87034352  939.77926088  704.29560193
  856.03115832  907.87224581 1211.42444524 1068.72365791  647.39196893
 1064.81679388  922.98354392  864.61559994 1122.33525777 1206.1999045
 1186.25602382  832.15649536  938.15752483 1066.25268628 1195.10902542]
The Units Sold is: [40 67 41 34 50 27 48 28 33 46 45 44 42 38 31 40 50 55 49 29 38 41 39 63
 53 55 37 36 54 58]


##### 2- Combine Data: 
###### Create a 2D NumPy array where the first column is sales_revenue and the second is units_sold.

In [10]:
sales_data = np.column_stack((sales_revenue, units_sold))
sales_data

array([[ 879.65867755,   40.        ],
       [1370.4556369 ,   67.        ],
       [ 997.30055505,   41.        ],
       [ 788.45781421,   34.        ],
       [1164.50898242,   50.        ],
       [ 755.83127001,   27.        ],
       [1041.772719  ,   48.        ],
       [ 608.06597522,   28.        ],
       [ 734.36279022,   33.        ],
       [1039.37224717,   46.        ],
       [1147.693316  ,   45.        ],
       [1034.27365624,   44.        ],
       [ 976.87034352,   42.        ],
       [ 939.77926088,   38.        ],
       [ 704.29560193,   31.        ],
       [ 856.03115832,   40.        ],
       [ 907.87224581,   50.        ],
       [1211.42444524,   55.        ],
       [1068.72365791,   49.        ],
       [ 647.39196893,   29.        ],
       [1064.81679388,   38.        ],
       [ 922.98354392,   41.        ],
       [ 864.61559994,   39.        ],
       [1122.33525777,   63.        ],
       [1206.1999045 ,   53.        ],
       [1186.25602382,   

##### 3- Key Performance Indicators (KPIs): 
###### Calculate the total sales_revenue for the month.

In [14]:
total_sales_revenue = np.sum(sales_revenue)
print("The total revenue:", total_sales_revenue)

The total revenue: 29273.025178260345


###### Calculate the average units_sold per day.

In [15]:
average_units_sold = np.mean(units_sold)
print("The averge sold is:", average_units_sold)

The averge sold is: 43.7


###### Determine the maximum daily sales_revenue and the day (index) it occurred.

In [26]:
max_sales_revenue  = np.max(sales_revenue)
max_daily_index = np.argmax(sales_revenue)

print("Max Revenue in a Day:", max_sales_revenue)
print("Day Index of Max Revenue:", max_daily_index)

Max Revenue in a Day: 1370.4556369017876
Day Index of Max Revenue: 1


###### Calculate the average revenue per unit sold for the entire month (total revenue / total units sold).

In [27]:
total_units_sold = np.sum(units_sold)
avg_revenue_per_unit = total_sales_revenue / total_units_sold

print("Average Revenue per Unit:", avg_revenue_per_unit)


Average Revenue per Unit: 22.328775879679895


##### 4 Conditional Analysis: 
###### Identify and count how many days had sales_revenue above a certain target (e.g., $1200).

In [28]:
days_above_1200 = sales_revenue > 1200
count_above_1200 = np.sum(days_above_1200)
count_above_1200

np.int64(3)

###### Calculate the average units_sold only for days when sales_revenue was below a certain threshold (e.g., $900).

In [29]:
days_below_900 = sales_revenue < 900
avg_units_below_900 = np.mean(units_sold[days_below_900])

print("Days below 900:", days_below_900)
print("The Average units below 900:", avg_units_below_900)

Days below 900: [ True False False  True False  True False  True  True False False False
 False False  True  True False False False  True False False  True False
 False False  True False False False]
The Average units below 900: 33.8


##### 5- Weekly Aggregations: 
###### Assume the 30 days start on a Monday. Calculate the total sales_revenue for each of the 4 full weeks (days 1-7, 8-14, 15-21, 22-28). You will need to reshape or carefully slice your data.

In [33]:
weekly_revenue_totals = []

for i in range(0, 28, 7):
    week_total = np.sum(sales_revenue[i:i+7])
    weekly_revenue_totals.append(week_total)

print("The total weekly revenue:", weekly_revenue_totals)

The total weekly revenue: [np.float64(6997.9856551445255), np.float64(6480.417589259753), np.float64(6460.555872019504), np.float64(7072.704350131377)]
