In [9]:
import numpy as np

NumPy Practice

Part 1: Array Creation and Properties

1.Create a 1D array named arr1d with integers from 0 to 9.

In [11]:
arr1d = np.arange(10)

In [12]:
print(arr1d)

[0 1 2 3 4 5 6 7 8 9]


2.Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [13]:
arr2d = np.full((3,3),1)

In [14]:
print(arr2d)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


3.Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [16]:
random_matrix = np.random.randn(3, 3)
print(random_matrix)

[[-0.78685201  0.96743308  1.50151269]
 [-0.79476256  0.34361036 -0.94189946]
 [-0.68613309  1.43347857 -1.53288692]]


4.Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [17]:
even_numbers = np.arange(10, 51, 2)
print(even_numbers)

[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


5.Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [18]:
linspace_array = np.linspace(0, 1, 7)
print(linspace_array)

[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


6.Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [19]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
shape = arr.shape
Dim = arr.ndim
Dtype = arr.dtype
print("Shape:", shape)   
print("Dimensions:", Dim)  
print("Data type:", Dtype) 

Shape: (2, 3)
Dimensions: 2
Data type: int64


Part 2: Array Manipulation

1.Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [20]:
reshaped_arr = arr1d.reshape(2, 5)
print(reshaped_arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]


2.Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [21]:
transposed_arr = reshaped_arr.T
print(transposed_arr)

[[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


3.Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [22]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_vertical = np.vstack((a, b))
print(stacked_vertical)

[[1 2 3]
 [4 5 6]]


4.Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [23]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
stacked_horizontal = np.hstack((m1, m2))
print(stacked_horizontal)

[[1 2 5 6]
 [3 4 7 8]]


5.Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [24]:
arr_to_split = np.arange(16).reshape(4, 4)
split_horizontal = np.hsplit(arr_to_split, 2)
print("First part:\n", split_horizontal[0])
print("Second part:\n", split_horizontal[1])

First part:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Second part:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


6.Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [25]:
split_vertical = np.vsplit(arr_to_split, 2)
print("First part:\n", split_vertical[0])
print("Second part:\n", split_vertical[1])

First part:
 [[0 1 2 3]
 [4 5 6 7]]
Second part:
 [[ 8  9 10 11]
 [12 13 14 15]]


Part 3: Indexing, Slicing, and Boolean Indexing

1.Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [26]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
element = data[1, 2]
print(element)

15


2.From the data array (from Q13), extract the first two rows and all columns.

In [30]:
subset = data[:2, :]
print(subset)

[[10 11 12]
 [13 14 15]]


3.From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [28]:
elements = data[[0, 1, 2], [1, 2, 1]]
print(elements)

[11 15 17]


4. Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [29]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print(high_scores)

[85 92 95 88]


Part 4: Numerical Operations and Aggregations

1.Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [31]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
mult = arr_op1 * arr_op2
div = arr_op1 / arr_op2
print("Multiplication:", mult)
print("Division:", div)

Multiplication: [ 20  80 180]
Division: [5. 5. 5.]


2.Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [33]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
total = np.sum(matrix)
print(total)

45


3.From the matrix (from Q18), calculate the mean of each column.

In [34]:
columnmeans = np.mean(matrix, axis=0)
print(columnmeans)

[4. 5. 6.]


4.Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [35]:
price = np.array([100, 150, 200, 250])
dprices = price* (1 - 0.10)
print(dprices)

[ 90. 135. 180. 225.]
