# Smart Building

Scenario: You are a data scientist monitoring environmental conditions in a smart building. You have collected sensor data (temperature, humidity, pressure) over 24 hours, with readings taken every minute. Your goal is to process this raw data to find key statistics and identify anomalies.

## Data Generation: 

In [1]:
import numpy as np
import pandas as pd

In [2]:
np.random.seed() 

In [3]:
timeMints = np.arange(1440)

In [4]:
temperature = np.random.uniform(20, 25) + np.random.normal(0, 1, size=1440)

In [5]:
humidity = np.clip(np.random.uniform(40, 60) + np.random.normal(0, 5, size=1440), 0, 100)

In [6]:
pressure = np.random.uniform(1008, 1015) + np.random.normal(0, 2, size=1440)

In [8]:
data = np.column_stack((timeMints, temperature, humidity, pressure))

In [9]:
print(data)

[[0.00000000e+00 2.25849005e+01 5.37437964e+01 1.01518172e+03]
 [1.00000000e+00 2.49814477e+01 5.35808797e+01 1.01151060e+03]
 [2.00000000e+00 2.52260574e+01 5.50912444e+01 1.01106502e+03]
 ...
 [1.43700000e+03 2.43850318e+01 6.19825795e+01 1.01124236e+03]
 [1.43800000e+03 2.48066285e+01 5.29023194e+01 1.00883947e+03]
 [1.43900000e+03 2.54493676e+01 5.06989054e+01 1.01459379e+03]]


## Basic Statistics: 

In [10]:
meanv = np.mean(data[:, 1:], axis=0)
print(meanv)

[  24.22477657   59.06895864 1012.49931352]


In [11]:
minv= np.min(data[:, 1:], axis=0)
print(minv)

[  20.82351531   43.88058668 1006.01371012]


In [12]:
maxv = np.max(data[:, 1:], axis=0)
print(maxv)

[  27.22511004   76.83600407 1018.26907479]


In [13]:
stdv = np.std(data[:, 1:], axis=0)
print(stdv)

[0.99029049 4.99941678 1.95547673]


## Hourly Averages: 

In [15]:
tempH = temperature.reshape(24, 60)
avgTempHour = np.mean(tempH, axis=1)
print(avgTempHour)

[24.37901472 24.28224853 24.00112743 24.23830253 24.13544736 24.34653997
 24.24171879 23.90279697 24.42805524 24.04817622 24.12928261 24.11057567
 24.34109738 24.37347726 24.23182786 24.18983794 24.18049189 24.28806913
 24.22746573 24.17609841 24.33676404 24.26367303 24.25660023 24.28594871]


In [16]:
humidH = humidity.reshape(24, 60)
avgHumidH = np.mean(humidH, axis=1)
print(avgHumidH)

[58.63476048 58.74804249 59.11713528 59.26405055 58.70564011 58.96797044
 59.17192187 58.60003992 59.51120459 59.75258774 60.03472465 59.73731331
 58.46562172 59.24459074 57.98821316 58.43476256 59.16089951 59.85604706
 58.46030952 59.41107689 58.78037131 59.05159701 58.37350656 60.18261993]


In [17]:
pressureH = pressure.reshape(24, 60)
avgPressureHour = np.mean(pressureH, axis=1)
print(avgPressureHour)

[1012.42124595 1012.54605209 1012.65519506 1012.49493229 1012.82508947
 1012.29557358 1012.5428807  1012.45937901 1012.02825877 1012.87987298
 1012.59515885 1012.4790785  1012.11583526 1012.60475701 1012.16566929
 1012.67928109 1012.23974401 1012.15388902 1012.59466953 1012.66728707
 1012.71554926 1012.390466   1012.83669807 1012.59696158]


## Anomaly Detection (Simple): 

In [19]:
threshold = 25
highTemp = np.where(temperature > threshold)[0]
numOfhighTemp = len(highTemp)
print(highTemp)
print(numOfhighTemp)

[   2    5    7    9   12   15   16   17   22   31   34   37   40   44
   47   53   55   56   58   62   65   71   73   79   83   87   89   93
  101  103  105  106  111  112  113  124  125  126  128  129  133  148
  158  189  199  203  205  212  213  221  225  226  230  238  240  243
  253  257  270  271  272  274  282  285  291  295  296  304  306  307
  313  323  324  325  332  338  349  351  352  355  358  364  372  384
  389  395  396  399  402  405  407  414  415  422  424  429  433  435
  439  452  467  482  484  488  491  500  502  505  508  509  510  512
  515  516  520  527  529  543  546  559  561  570  578  581  584  589
  593  595  600  614  615  620  625  629  635  647  650  655  657  658
  668  673  674  677  679  684  688  691  694  699  711  721  729  740
  743  746  749  750  752  755  758  761  762  764  771  773  775  777
  778  779  783  784  790  792  794  805  809  811  814  818  819  823
  824  825  828  835  836  840  841  849  855  857  858  865  871  872
  877 

In [20]:
minTempIndex = np.argmin(temperature)
print(minTempIndex)
minTempTime = timeMints[minTempIndex]
print(minTempTime)

851
851


## Data Export (Optional): 

In [21]:
header = "Time,Temperature,Humidity,Pressure"
np.savetxt("SmartBuildingData.csv", data, delimiter=",", header=header, comments='', fmt='%.2f')