# This is the first Notebook
## tesk
### Malik
__hi__
*hello*
* point 1
* point 2
  * point 2.1



In [3]:
print("hello world")

hello world


[open this link](https://www.youtube.com/watch?v=suAkMeWJ1yE)

In [17]:
def get_even_numbers(numbers):
    even_numbers = []
    for number in numbers:
        if number % 2 == 0:
            even_numbers.append(number)
    return even_numbers

In [18]:
user_input = input("Enter numbers separated by commas: ")
numbers = [int(num.strip()) for num in user_input.split(",")]
result = get_even_numbers(numbers)
print(result)

Enter numbers separated by commas:  1,2,3,4,5,6


[2, 4, 6]


In [20]:
import numpy as np

In [21]:
list_1d = (1,2,3,4)
arr_1d = np.array(list_1d)
arr_1d.dtype

dtype('int64')

In [22]:
arr_1d.ndim

1

Create a 1D array named arr1d with integers from 0 to 9.

In [23]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [24]:
arr2d = np.ones((3, 3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [25]:
random_matrix = np.random.randn(3, 3)
random_matrix

array([[-0.12311028, -0.48405518, -1.07244637],
       [-0.26908754, -0.09678387,  0.32800229],
       [ 1.42413043,  2.15252656,  0.40914011]])

Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).
 

In [26]:
even_numbers = np.arange(10, 52, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [27]:
linspace_array = np.linspace(0, 1, 7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [28]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape:", arr.shape)
print("Number of dimensions (ndim):", arr.ndim)
print("Data type (dtype):", arr.dtype)

Shape: (2, 3)
Number of dimensions (ndim): 2
Data type (dtype): int64


Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [29]:
reshaped_arr = arr1d.reshape(2,5)
print ("reshaped_arr:\n", reshaped_arr)

reshaped_arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [30]:
transposed_arr = reshaped_arr.T
print("transposed_arr:\n", transposed_arr)

transposed_arr:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_vertical = np.vstack((a,b))
print("Vertically stacked:\n", stacked_vertical)

Vertically stacked:
 [[1 2 3]
 [4 5 6]]


Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [35]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
stacked_horizontal = np.hstack((m1, m2))
print("Horizontally stacked:\n", stacked_horizontal)

Horizontally stacked:
 [[1 2 5 6]
 [3 4 7 8]]


Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [36]:
arr_to_split = np.arange(16).reshape(4, 4)
split_h = np.hsplit(arr_to_split, 2)
print("First half horizontally:\n", split_h[0])
print("Second half horizontally:\n", split_h[1])


First half horizontally:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Second half horizontally:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [37]:
split_v = np.vsplit(arr_to_split, 2)
print("First half vertically:\n", split_v[0])
print("Second half vertically:\n", split_v[1])


First half vertically:
 [[0 1 2 3]
 [4 5 6 7]]
Second half vertically:
 [[ 8  9 10 11]
 [12 13 14 15]]


Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [38]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
element = data[1, 2]
print("Element at row 1, column 2:", element)


Element at row 1, column 2: 15


From the data array (from Q13), extract the first two rows and all columns.

In [39]:
first_two_rows = data[:2, :]
print("First two rows:\n", first_two_rows)


First two rows:
 [[10 11 12]
 [13 14 15]]


From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [40]:
elements = data[[0, 1, 2], [1, 2, 1]]
print("Selected elements:", elements)


Selected elements: [11 15 17]


Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [41]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print("Scores > 80:", high_scores)


Scores > 80: [85 92 95 88]


Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [42]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
print("Multiplication:", arr_op1 * arr_op2)
print("Division:", arr_op1 / arr_op2)


Multiplication: [ 20  80 180]
Division: [5. 5. 5.]


Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [43]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
total_sum = matrix.sum()
print("Total sum:", total_sum)


Total sum: 45


From the matrix (from Q18), calculate the mean of each column.

In [44]:
column_means = matrix.mean(axis=0)
print("Column means:", column_means)


Column means: [4. 5. 6.]


Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [45]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discounted_prices = price_array * (1 - discount_percentage)
print("Discounted prices:", discounted_prices)


Discounted prices: [ 90. 135. 180. 225.]
