# Numpy Excercise

In [45]:
import numpy as np

# Part 1

### Array Creation and Properties

**Question 1: Create a 1D array named arr1d with integers from 0 to 9**

In [28]:
arr1d = np.arange (0,10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

**Question 2: Create a 2D array named arr2d with shape (3, 3) filled with ones**

In [31]:
arr2d = np.ones((3,3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**Question 3: Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution**

In [36]:
random_matrix =np.random.rand(3,3)
random_matrix

array([[0.58005324, 0.33344649, 0.71635006],
       [0.42387681, 0.64176544, 0.8785958 ],
       [0.97213272, 0.47995574, 0.18804675]])

**Question 4: Create an array named even_numbers containing even numbers from 10 to 50 (inclusive)**

In [38]:
even_numbers =np.arange(10, 51, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

**Question 5: Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive)**

In [39]:
linspace_array =np.linspace(0,1,7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

**Question 6: Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them**

In [79]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('Shape:',arr.shape)
print('ndim:',arr.ndim)
print('dtype:',arr.dtype)

Shape: (2, 3)
ndim: 2
dtype: int64


# Part 2

### Array Manipulation

**Question7: Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr**

In [48]:
arr1d = np.arange (0,10)
reshaped_arr =arr1d.reshape((2,5))
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

**Question8: Transpose reshaped_arr (from Q7). Name the result transposed_arr**

In [49]:
transposed_arr =reshaped_arr.T
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

**Question9: Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically**

In [50]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

v_stack =np.vstack((a,b))
v_stack

array([[1, 2, 3],
       [4, 5, 6]])

**Question10: Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally**

In [51]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

h_stack =np.hstack((m1,m2))
h_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

**Question11: Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts**

In [80]:
arr_to_split = np.arange(16).reshape(4, 4)
left, right =np.hsplit(arr_to_split, 2)
print('Left part:')
print(left)
print('Right part:')
print(right)

Left part:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Right part:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


**Qustion12: Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts**

In [81]:
arr_to_split = np.arange(16).reshape(4, 4)
top, bottom =np.vsplit(arr_to_split, [2])
print('Top part:')
print(top)
print('Bottom part:')
print(bottom)

Top part:
[[0 1 2 3]
 [4 5 6 7]]
Bottom part:
[[ 8  9 10 11]
 [12 13 14 15]]


# Part 3

### Indexing, Slicing, and Boolean Indexing

**Question13: Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2**

In [55]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(data[1, 2])

15


**Question14: From the data array (from Q13), extract the first two rows and all columns**

In [82]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(data[ :2, : ])

[[10 11 12]
 [13 14 15]]


**Question15: From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns)**

In [83]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
rows = np.array([0, 1, 2])
cols = np.array([1, 2, 1])

elements = data[rows, cols]
print(elements)

[11 15 17]


**Question16: Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80**

In [84]:
scores = np.array([85, 92, 78, 65, 95, 88])
filtered_scores = scores[scores > 80]
print(filtered_scores)

[85 92 95 88]


# Part 4

### Numerical Operations and Aggregations

**Question17: Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2)**

In [65]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
print('Multiplication:\n', arr_op1 * arr_op2)
print('Division:\n', arr_op1 / arr_op2)

Multiplication:
 [ 20  80 180]
Division:
 [5. 5. 5.]


**Question18: Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix**

In [71]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Total_elements =np.sum(matrix)
Total_elements

np.int64(45)

**Question19: From the matrix (from Q18), calculate the mean of each column**

In [74]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
column_mean =np.mean(matrix, axis=0)
column_mean

array([4., 5., 6.])

**Question20: Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting**

In [77]:
price_array = np.array([100, 150, 200, 250])
discounted = price_array * ( 1 - 0.10)
discounted

array([ 90., 135., 180., 225.])