# 1. Sales Data Generation: 

In [25]:
import numpy as np

base_revenue = 1000
fluctuation = np.random.normal(0, 300, size=30)
sales_revenue = np.maximum(base_revenue + fluctuation, 0)

print("\nSales Revenue:")
print(np.round(sales_revenue, 2))
price_unit= 50

units_sold =(sales_revenue//50)

print("\nUnits Sold:")
print(units_sold)



Sales Revenue:
[1381.65  773.24 1259.21 1168.62  976.03 1605.53 1332.1   800.46 1400.68
  631.72  750.81  747.02  688.88 1527.17 1250.15 1286.46 1249.66  611.89
 1540.57 1653.44  812.19  589.47 1524.53  810.9   803.65 1153.24 1006.4
 1064.76 1219.91  671.5 ]

Units Sold:
[27. 15. 25. 23. 19. 32. 26. 16. 28. 12. 15. 14. 13. 30. 25. 25. 24. 12.
 30. 33. 16. 11. 30. 16. 16. 23. 20. 21. 24. 13.]


# 2. Combine Data: 

In [33]:
Sales_Revenue_2D = sales_revenue.reshape(10, 3)
print(Sales_Revenue_2D)
units_sold_2D= units_sold.reshape(10, 3)
print(units_sold_2D)


[[1381.6544617   773.24119305 1259.21357491]
 [1168.61883518  976.02872693 1605.53371374]
 [1332.10471484  800.45810863 1400.67959622]
 [ 631.72057892  750.81212046  747.02101357]
 [ 688.87905426 1527.16605413 1250.14933389]
 [1286.45758642 1249.66456405  611.89419911]
 [1540.56868623 1653.44317304  812.19477397]
 [ 589.46797329 1524.53422689  810.90028372]
 [ 803.65343792 1153.2402848  1006.40297037]
 [1064.76293922 1219.91499689  671.49709218]]
[[27. 15. 25.]
 [23. 19. 32.]
 [26. 16. 28.]
 [12. 15. 14.]
 [13. 30. 25.]
 [25. 24. 12.]
 [30. 33. 16.]
 [11. 30. 16.]
 [16. 23. 20.]
 [21. 24. 13.]]


# 3. Key Performance Indicators (KPIs): 

In [111]:
sales_revenue_sumation_total = np.sum(sales_revenue)
print("")
print(sales_revenue_sumation_total)
units_sold_mean =int(np. mean(units_sold))
print("the mean of the units sold: ")
print(units_sold_mean)
sales_revenue_max =np.max(sales_revenue)
print("\nthe maxmim revenue in a day was: ")
print(sales_revenue_max)
day_index = np.argmax(sales_revenue)  
print("\nDay of max revenue:")
print(day_index + 1) 



32291.87826852653
the mean of the units sold: 
21

the maxmim revenue in a day was: 
1653.4431730381411

Day of max revenue:
20


In [38]:
sales_revenue_above_1200= sales_revenue>1200
sales_revenue_above_1200

array([ True, False,  True, False, False,  True,  True, False,  True,
       False, False, False, False,  True,  True,  True,  True, False,
        True,  True, False, False,  True, False, False, False, False,
       False,  True, False])

In [100]:
above_1200 = sales_revenue[sales_revenue_above_1200]
print("the days that reach above 1200:\n",above_1200)

the days that reach above 1200:
 [1381.6544617  1259.21357491 1605.53371374 1332.10471484 1400.67959622
 1527.16605413 1250.14933389 1286.45758642 1249.66456405 1540.56868623
 1653.44317304 1524.53422689 1219.91499689]


In [74]:

days_above_target = np.sum(sales_revenue >1200)
print("\nnumber of days (above 1200):")
print(days_above_target)

number of days (above 1200):
13


In [97]:
sales_revenue_below_900 = sales_revenue< 900 
below_900 = sales_revenue[sales_revenue_below_900]
print("\nnumber of days are:")
print(np.sum(sales_revenue< 900))
sumation_below_900 = np.sum(below_900)
print("\ntotal sumation of the items below 900 : ")
print(sumation_below_900)


number of days are:
12

total sumation of the items below 900 : 
8691.739829080401


# 4. Weekly Aggregations: 

In [96]:
first_week = np.round(sales_revenue[0:7], 2)
print ("\nfirst week:")
print(first_week)

secound_week = np.round(sales_revenue[7:14], 2)
print("\nsecoud week:")
print(secound_week)

therd_week = np.round(sales_revenue[14:21], 2)
print("\ntherd week:")
print(therd_week)

forth_week = np.round(sales_revenue[21:28], 2)
print("\nforth week:")
print(forth_week)


first week:
[1381.65  773.24 1259.21 1168.62  976.03 1605.53 1332.1 ]

secoud week:
[ 800.46 1400.68  631.72  750.81  747.02  688.88 1527.17]

therd week:
[1250.15 1286.46 1249.66  611.89 1540.57 1653.44  812.19]

forth week:
[ 589.47 1524.53  810.9   803.65 1153.24 1006.4  1064.76]
