In [2]:
import numpy as np

np.random.seed(42)


time_in_minutes = np.arange(1440)

temperature = 22 + np.random.normal(0, 1, size=1440)


humidity = np.clip(55 + np.random.normal(0, 5, size=1440), 0, 100)

pressure = 1012 + np.random.normal(0, 1.5, size=1440)


data = np.column_stack((time_in_minutes, temperature, humidity, pressure))

print("Sample data (first 5 rows):\n", data[:5])


Sample data (first 5 rows):
 [[0.00000000e+00 2.24967142e+01 5.83144063e+01 1.00864265e+03]
 [1.00000000e+00 2.18617357e+01 6.08673693e+01 1.00881895e+03]
 [2.00000000e+00 2.26476885e+01 5.59051078e+01 1.01108970e+03]
 [3.00000000e+00 2.35230299e+01 4.85158403e+01 1.01268653e+03]
 [4.00000000e+00 2.17658466e+01 5.69984398e+01 1.00787874e+03]]


In [3]:

avg_vals = np.mean(data[:, 1:], axis=0)
min_vals = np.min(data[:, 1:], axis=0)
max_vals = np.max(data[:, 1:], axis=0)
std_vals = np.std(data[:, 1:], axis=0)

print("\n--- Basic Statistics ---")
print(f"Average (Temp, Humidity, Pressure): {avg_vals}")
print(f"Min     (Temp, Humidity, Pressure): {min_vals}")
print(f"Max     (Temp, Humidity, Pressure): {max_vals}")
print(f"Std Dev (Temp, Humidity, Pressure): {std_vals}")



--- Basic Statistics ---
Average (Temp, Humidity, Pressure): [  22.03984422   55.13280172 1011.94350103]
Min     (Temp, Humidity, Pressure): [  18.75873266   39.90243922 1007.48855149]
Max     (Temp, Humidity, Pressure): [  25.85273149   70.96553784 1017.88935656]
Std Dev (Temp, Humidity, Pressure): [0.98698992 4.88551178 1.54002997]


In [4]:
temp_hourly = temperature.reshape(24, 60).mean(axis=1)
hum_hourly = humidity.reshape(24, 60).mean(axis=1)
pres_hourly = pressure.reshape(24, 60).mean(axis=1)

print("\nHourly Average Temperature (°C):\n", temp_hourly)
print("\nHourly Average Humidity (%):\n", hum_hourly)
print("\nHourly Average Pressure (hPa):\n", pres_hourly)


Hourly Average Temperature (°C):
 [21.84534532 21.99631657 22.09191425 22.05681427 21.98186679 22.03766373
 22.12846891 21.99459841 21.73265389 21.99916515 22.09802374 21.9159646
 21.99356816 22.08837099 22.31504311 22.09480545 22.09622643 22.06653541
 22.27836492 21.95593422 22.03284943 22.04130045 21.86207923 22.25238787]

Hourly Average Humidity (%):
 [56.34988691 55.00050036 54.37000735 56.15403255 55.6167704  54.92926533
 54.59825751 54.92600369 55.5013707  54.77826287 54.5783234  54.84173458
 55.24161721 54.58633043 56.14538871 53.90432668 55.30261021 55.30449767
 55.49893437 55.44029956 54.72809495 56.39890599 54.25960382 54.73221607]

Hourly Average Pressure (hPa):
 [1012.02414135 1011.985357   1011.6098628  1012.12049981 1011.56069136
 1012.15713168 1012.14108932 1012.17013856 1012.02176369 1012.06446902
 1011.9272415  1012.22100309 1011.93747566 1012.39009987 1011.61467244
 1011.60032006 1011.83189107 1012.09006912 1011.88396424 1011.87589926
 1012.16425307 1011.74992698 101

In [5]:
high_temp_mask = temperature > 25
high_temp_minutes = np.sum(high_temp_mask)

min_temp_time = time_in_minutes[np.argmin(temperature)]

print("\n--- Anomaly Detection ---")
print(f"Minutes with temperature > 25°C: {high_temp_minutes}")
print(f"Time (in minutes) of min temperature: {min_temp_time}")


--- Anomaly Detection ---
Minutes with temperature > 25°C: 2
Time (in minutes) of min temperature: 262


In [6]:
np.savetxt("smart_building_data.csv", data, delimiter=",", 
           header="Time,Temperature,Humidity,Pressure", comments='')
print("\nData exported to 'smart_building_data.csv'")


Data exported to 'smart_building_data.csv'
