# NumPy Practice

In [2]:
import numpy as np

#### part 1 : 
###### Create a 1D array named arr1d with integers from 0 to 9.

In [4]:
arr1d = np.arange(0,10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

###### Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [5]:
arr2d = np.ones ((3,3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

###### Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [7]:
random_matrix = np.random.randn (3,3) # this is for random distribution 
random_matrix

array([[ 1.07257826,  1.01804696,  1.01756432],
       [ 0.40500576, -0.88618305, -0.18244006],
       [-1.13770712, -0.63818186,  1.0154555 ]])

###### Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [9]:
even_numbers = np.arange(10,51,2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

###### Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [10]:
linspace_array = np.linspace (0,1,7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

###### Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [12]:
 arr = np.array([[1, 2, 3], [4, 5, 6]])

In [13]:
arr.shape

(2, 3)

In [14]:
arr.ndim

2

In [15]:
arr.dtype

dtype('int64')

#### Part 2: Array Manipulation

###### Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [16]:
reshaped_arr = arr1d.reshape(2,5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

###### Transpose reshaped_arr (from Q7). Name the result transposed_arr.


In [17]:
transposed_arr = reshaped_arr.T
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

###### Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [18]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
v_stack = np.vstack((a,b))
v_stack

array([[1, 2, 3],
       [4, 5, 6]])

###### Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [19]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]]) 
h_stack = np.hstack((m1,m2))
h_stack


array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

###### Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [21]:
arr_to_split = np.arange(16).reshape(4, 4)
arr = np.hsplit(arr_to_split,2)
for part in arr:
    print(part)
    print("____")

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
____
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
____


###### Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [22]:
arr_to_split = np.arange(16).reshape(4, 4)
arr = np.vsplit(arr_to_split,2)
for part in arr:
    print(part)
    print("____")

[[0 1 2 3]
 [4 5 6 7]]
____
[[ 8  9 10 11]
 [12 13 14 15]]
____


##### Part 3: Indexing, Slicing, and Boolean Indexing

###### Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.


In [9]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
_data = data[1,2]
_data

np.int64(15)

###### From the data array (from Q13), extract the first two rows and all columns.

In [11]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
split_data = data[:2,]
split_data

array([[10, 11, 12],
       [13, 14, 15]])

###### From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns)

In [13]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
split_data = data[[0,1,2],[1,2,1]] # fisrt part is for rows and second for columns each column start from 0 but the rows goes like all pracket
split_data

array([11, 15, 17])

###### Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [16]:
scores = np.array([85, 92, 78, 65, 95, 88])
condition = scores > 80
scores_index = scores[condition]
scores_index

array([85, 92, 95, 88])

##### Part 4: Numerical Operations and Aggregations

###### Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [18]:
arr_op1 = np.array([10, 20, 30]) 
arr_op2 = np.array([2, 4, 6])
mult = arr_op1 * arr_op2
div = arr_op1 / arr_op2
print ("multiplication array value : \n " , mult)
print ("division array value : \n " , div)

multiplication array value : 
  [ 20  80 180]
division array value : 
  [5. 5. 5.]


###### Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [20]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_sum = matrix.sum()
matrix_sum

np.int64(45)

###### From the matrix (from Q18), calculate the mean of each column.

In [21]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_mean = matrix.mean(axis = 0) # tha axis goes one column by one
matrix_mean

array([4., 5., 6.])

###### Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.


In [23]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
condition = price_array * (1-discount_percentage)
#masked = np.ma.masked_array(price_array, mask = condition)

condition

array([ 90., 135., 180., 225.])