# **NumPy Practice**

##### Importing ```NumPy``` 

In [2]:
import numpy as np

### **Part 1:** Array Creation and Properties
##### 1. Create a 1D array named ```arr1d``` with integers ```from 0 to 9```

In [3]:
arr1d = np.arange(0,10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 2. Create a 2D array named ```arr2d``` with shape ```(3, 3)``` filled with ```ones```

In [4]:
arr2d = np.ones((3,3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### 3. Create a ```3x3``` array named ```random_matrix``` with random floating-point numbers from a standard normal distribution

In [5]:
random_matrix = np.random.randn(3, 3)
random_matrix

array([[-0.01433273,  0.43249479, -0.57354159],
       [-1.13390544,  0.6250827 ,  0.05759547],
       [-1.12817958,  0.82194981,  0.01474677]])

##### 4. Create an array named ```even_numbers``` containing even numbers ```from 10 to 50 (inclusive)```

In [6]:
even_numbers = np.arange(10, 51, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

##### 5. Create an array named ```linspace_array``` containing ```7``` equally spaced numbers ```between 0 and 1 (inclusive)```

In [7]:
linspace_array = np.linspace(0, 1, 7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

##### 6. Given ```arr = np.array([[1, 2, 3], [4, 5, 6]])```, what is its shape, ndim, and dtype? Print them

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(2, 3)
2
int32


### Part 2: Array Manipulation
##### 7. Reshape arr1d (from Q1) into a ```2x5``` 2D array. Name the new array ```reshaped_arr```

In [9]:
reshaped_arr = arr1d.reshape(2, 5)
print("reshaped_arr:\n", reshaped_arr)

reshaped_arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


##### 8. Transpose ```reshaped_arr``` (from Q7). Name the result ```transposed_arr```

In [10]:
transposed_arr = reshaped_arr.T
print("transposed_arr:\n", transposed_arr)

transposed_arr:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


##### 9. Stack two 1D arrays ```a = np.array([1, 2, 3])``` and ```b = np.array([4, 5, 6])``` vertically

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_vertically = np.vstack((a, b))
print("Vertically Stacked:\n", stacked_vertically)

Vertically Stacked:
 [[1 2 3]
 [4 5 6]]


##### 10. Stack two 2D arrays ```m1 = np.array([[1, 2], [3, 4]])``` and ```m2 = np.array([[5, 6], [7, 8]])``` horizontally.

In [12]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
stacked_horizontally = np.hstack((m1, m2))
print("Horizontally Stacked:\n", stacked_horizontally)

Horizontally Stacked:
 [[1 2 5 6]
 [3 4 7 8]]


##### 11. Split the array ```arr_to_split = np.arange(16).reshape(4, 4)``` horizontally into 2 equal parts. Print both parts

In [14]:
arr_to_split = np.arange(16).reshape(4, 4)
arr_to_split

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
h_split = np.hsplit(arr_to_split, 2)
print("Horizontal Split - Part 1:\n", h_split[0])
print("Horizontal Split - Part 2:\n", h_split[1])

Horizontal Split - Part 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Horizontal Split - Part 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


##### 12. Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts

In [16]:
v_split = np.vsplit(arr_to_split, 2)
print("Vertical Split - Part 1:\n", v_split[0])
print("Vertical Split - Part 2:\n", v_split[1])

Vertical Split - Part 1:
 [[0 1 2 3]
 [4 5 6 7]]
Vertical Split - Part 2:
 [[ 8  9 10 11]
 [12 13 14 15]]


### Part 3:  Indexing, Slicing, and Boolean Indexing
##### 13. Given ```data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])```, extract the element at row 1, column 2

In [18]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
element = data[1, 2]
print("Element:", element)

Element: 15


##### 14. From the data array (from Q13), extract the first two rows and all columns

In [19]:
part = data[:2, :]
print("First two rows:\n", part)

First two rows:
 [[10 11 12]
 [13 14 15]]


##### 15. From the data array (from Q13), extract the elements ```11, 15, and 17``` using fancy indexing (hint: you'll need to specify rows and columns)

In [22]:
fancy = data[[0, 1, 2], [1, 2, 1]] # data[[R1,R2,R3], [C1,C2,C3]]
print("Fancy Indexed Elements:", fancy)

Fancy Indexed Elements: [11 15 17]


##### 16. Given ```scores = np.array([85, 92, 78, 65, 95, 88])```, use boolean indexing to find all scores greater than 80

In [23]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print("Scores > 80:", high_scores)

Scores > 80: [85 92 95 88]


### Part 4: Numerical Operations and Aggregations
##### 17. Given ```arr_op1 = np.array([10, 20, 30])``` and ```arr_op2 = np.array([2, 4, 6])```, perform element-wise multiplication and division ```(arr_op1 / arr_op2)```

In [24]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
product = arr_op1 * arr_op2
division = arr_op1 / arr_op2
print("Multiplication:", product)
print("Division:", division)

Multiplication: [ 20  80 180]
Division: [5. 5. 5.]


##### 18. Given ```matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])```, calculate the sum of all elements in the matrix

In [25]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
total = matrix.sum()
print("Sum:", total)

Sum: 45


##### 19. From the matrix (from Q18), calculate the mean of each column

In [26]:
column_means = matrix.mean(axis=0)
print("Mean of each column:", column_means)
''' 
Column 0: mean = (1+4+7)/3 = 4
Column 1: mean = (2+5+8)/3 = 5
Column 2: mean = (3+6+9)/3 = 6
'''

Mean of each column: [4. 5. 6.]


##### 20. Given ```price_array = np.array([100, 150, 200, 250])``` and ```discount_percentage = 0.10```, apply a 10% discount to all prices using broadcasting

In [27]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discounted_prices = price_array * (1 - discount_percentage)
print("Discounted Prices:", discounted_prices)

Discounted Prices: [ 90. 135. 180. 225.]
