# <span style = "color:red">NumPy Practice</span>
#### Maha Al Yahmadi

#### <span style = "color:blue">Part 1</span>

In [10]:
import numpy as np

In [2]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr2d = np.ones((3, 3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
random_matrix = np.random.randn(3, 3)
random_matrix

array([[ 0.35914072,  0.09124544,  1.23015197],
       [-0.0148593 , -0.39855036,  0.81569353],
       [ 0.66290162,  1.72744732, -2.08687339]])

In [5]:
even_numbers = np.arange(10, 51, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [6]:
linspace_array = np.linspace(0, 1, 7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape, arr.ndim, arr.dtype

((2, 3), 2, dtype('int64'))

#### <span style = "color:blue">Part 2</span>

In [11]:
arr1d = np.arange(10) 
reshaped_arr = arr1d.reshape((2, 5))
print("Here’s arr1d reshaped to 2 rows x 5 columns:\n", reshaped_arr)

Here’s arr1d reshaped to 2 rows x 5 columns:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [12]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

stacked_vert = np.vstack((a, b))
print("\nStacking arrays a and b vertically:\n", stacked_vert)


Stacking arrays a and b vertically:
 [[1 2 3]
 [4 5 6]]


In [13]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])

stacked_horiz = np.hstack((m1, m2))
print("\nStacking m1 and m2 side by side (horizontally):\n", stacked_horiz)


Stacking m1 and m2 side by side (horizontally):
 [[1 2 5 6]
 [3 4 7 8]]


In [14]:
arr_to_split = np.arange(16).reshape(4, 4)
print("\nOriginal 4x4 array:\n", arr_to_split)

split_h = np.hsplit(arr_to_split, 2)
print("\nFirst half after horizontal split:\n", split_h[0])
print("\nSecond half after horizontal split:\n", split_h[1])


Original 4x4 array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

First half after horizontal split:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

Second half after horizontal split:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [15]:
split_v = np.vsplit(arr_to_split, [2])
print("\nTop part after vertical split at row index 2:\n", split_v[0])
print("\nBottom part after vertical split at row index 2:\n", split_v[1])


Top part after vertical split at row index 2:
 [[0 1 2 3]
 [4 5 6 7]]

Bottom part after vertical split at row index 2:
 [[ 8  9 10 11]
 [12 13 14 15]]


#### <span style = "color:blue">Part 3</span>

In [16]:
import numpy as np

data = np.array([
    [10, 11, 12],
    [13, 14, 15],
    [16, 17, 18]
])
elem = data[1, 2]
print(f"Element at row 1, column 2 is: {elem}")

Element at row 1, column 2 is: 15


In [17]:
rows_1_2 = data[:2, :]
print("\nHere are the first two rows:\n", rows_1_2)


Here are the first two rows:
 [[10 11 12]
 [13 14 15]]


In [19]:
rows = [0, 1, 2]
cols = [1, 2, 1]

picked = data[rows, cols]
print("\nElements 11, 15, 17 selected using fancy indexing:\n", picked)


Elements 11, 15, 17 selected using fancy indexing:
 [11 15 17]


In [20]:
scores = np.array([85, 92, 78, 65, 95, 88])

above_80 = scores[scores > 80]
print("\nScores higher than 80 are:\n", above_80)


Scores higher than 80 are:
 [85 92 95 88]


#### <span style = "color:blue">Part 4</span>

In [21]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])

multiplied = arr_op1 * arr_op2
print("Element-wise multiplication:", multiplied)

divided = arr_op1 / arr_op2
print("Element-wise division:", divided)

Element-wise multiplication: [ 20  80 180]
Element-wise division: [5. 5. 5.]


In [25]:
matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
total_sum = np.sum(matrix)
print("\nTotal sum of all elements in matrix:", total_sum)


Total sum of all elements in matrix: 45


In [23]:
col_mean = np.mean(matrix, axis=0)
print("\nMean of each column:", col_mean)


Mean of each column: [4. 5. 6.]


In [24]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10

discounted_prices = price_array * (1 - discount_percentage)
print("\nPrices after 10% discount:", discounted_prices)


Prices after 10% discount: [ 90. 135. 180. 225.]
