In [1]:
import numpy as np

In [2]:

total_minutes = 1440
minutes = np.arange(total_minutes)

# Temperature
temperature = 22 + np.random.normal(0, 2, total_minutes)

# Humidity
humidity = 55 + np.random.normal(0, 5, total_minutes)
humidity = np.clip(humidity, 0, 100)

# Pressure
pressure = 1012 + np.random.normal(0, 3, total_minutes)

sensor_data = np.column_stack((minutes, temperature, humidity, pressure))

print(sensor_data[:10])

[[0.00000000e+00 2.44763690e+01 6.43706243e+01 1.01220497e+03]
 [1.00000000e+00 2.16438105e+01 6.09992555e+01 1.01519534e+03]
 [2.00000000e+00 2.26560857e+01 4.80988578e+01 1.01619218e+03]
 [3.00000000e+00 2.10980040e+01 5.86720121e+01 1.01318840e+03]
 [4.00000000e+00 2.41069355e+01 4.55197908e+01 1.01218462e+03]
 [5.00000000e+00 2.07916169e+01 5.03203448e+01 1.01500038e+03]
 [6.00000000e+00 2.21525082e+01 4.54131788e+01 1.00991315e+03]
 [7.00000000e+00 2.14655319e+01 6.34823387e+01 1.01111901e+03]
 [8.00000000e+00 2.50642958e+01 5.45691534e+01 1.00639311e+03]
 [9.00000000e+00 2.20053971e+01 5.76196179e+01 1.00781678e+03]]


In [3]:
# Temperature
temp_avg = np.mean(temperature)
temp_min = np.min(temperature)
temp_max = np.max(temperature)
temp_std = np.std(temperature)

#Humidity
hum_avg = np.mean(humidity)
hum_min = np.min(humidity)
hum_max = np.max(humidity)
hum_std = np.std(humidity)

#Pressure
press_avg = np.mean(pressure)
press_min = np.min(pressure)
press_max = np.max(pressure)
press_std = np.std(pressure)


print("Temperature average:", temp_avg)
print("Temperature minimum:", temp_min)
print("Temperature maximum:", temp_max)
print("Temperature standard deviation:", temp_std)

print ("___________________________________________________")

print("Humidity average:", hum_avg)
print("Humidity minimum:", hum_min)
print("Humidity maximum:", hum_max)
print("Humidity standard deviation:", hum_std)

print ("___________________________________________________")

print("Pressure average:", press_avg)
print("Pressure minimum:", press_min)
print("Pressure maximum:", press_max)
print("Pressure standard deviation:", press_std)


Temperature average: 22.02452507490211
Temperature minimum: 13.357060249008057
Temperature maximum: 29.181206185660894
Temperature standard deviation: 2.105792147679967
___________________________________________________
Humidity average: 55.21244119387555
Humidity minimum: 36.91957793223719
Humidity maximum: 70.62115108934918
Humidity standard deviation: 4.97453487119157
___________________________________________________
Pressure average: 1011.9858452433502
Pressure minimum: 1002.1163833883376
Pressure maximum: 1021.6214153465967
Pressure standard deviation: 2.9941829990027924


In [4]:
temp_per_hour = temperature.reshape(24, 60)
hum_per_hour = humidity.reshape(24, 60)
press_per_hour = pressure.reshape(24, 60)

temp_hour_avg = np.mean(temp_per_hour, axis=1)
hum_hour_avg = np.mean(hum_per_hour, axis=1)
press_hour_avg = np.mean(press_per_hour, axis=1)

print("\nTemperature hourly averages:", temp_hour_avg)
print("____________________________________________________________________")
print("\nHumidity hourly averages:", hum_hour_avg)
print("____________________________________________________________________")
print("\nPressure hourly averages:", press_hour_avg)


Temperature hourly averages: [22.03967184 21.81147972 22.23703856 21.80507997 22.13579581 21.99715426
 22.05286361 21.86285768 22.15489856 22.5003084  22.23508244 21.96784106
 21.94033318 21.88576602 21.93175239 21.95902889 21.71786428 21.76958049
 22.27544562 22.46437852 21.97299417 22.10952013 21.71411346 22.04775276]
____________________________________________________________________

Humidity hourly averages: [55.51499736 53.78036355 54.59006064 55.03893738 55.21218511 56.0402103
 56.06065065 55.89871306 55.90766612 54.3405445  54.450486   55.57955126
 54.98566708 54.82070281 54.77862358 54.50511626 55.51601573 55.63666654
 55.38001385 55.54222395 54.93226293 55.57862499 54.74098487 56.26732014]
____________________________________________________________________

Pressure hourly averages: [1011.76974519 1011.91404306 1011.96580852 1011.62209852 1011.3157635
 1011.99380342 1011.80965678 1011.78707356 1011.92031837 1011.44709407
 1011.61530324 1011.78690377 1012.54261717 1011.9671

In [5]:
limit = 25

high_temp_count = np.sum(temperature > limit)
minute_of_min_temp = minutes[np.argmin(temperature)]

print("\nNumber of Minutes with temperature higher than", limit, ":", high_temp_count)
print("\nMinute when temperature was the lowest:", minute_of_min_temp)



Number of Minutes with temperature higher than 25 : 115

Minute when temperature was the lowest: 665
