In [3]:
import numpy as np

In [ ]:

total_minutes = 1440
minutes = np.arange(total_minutes)

# Temperature
temperature = 22 + np.random.normal(0, 2, total_minutes)

# Humidity
humidity = 55 + np.random.normal(0, 5, total_minutes)
humidity = np.clip(humidity, 0, 100)

# Pressure
pressure = 1012 + np.random.normal(0, 3, total_minutes)

sensor_data = np.column_stack((minutes, temperature, humidity, pressure))

print(sensor_data[:10])

[[0.00000000e+00 2.27146631e+01 5.56636384e+01 1.01092306e+03]
 [1.00000000e+00 2.33239440e+01 4.86500367e+01 1.01024186e+03]
 [2.00000000e+00 2.13192238e+01 6.13600521e+01 1.01646099e+03]
 [3.00000000e+00 2.39901916e+01 6.07411149e+01 1.01061481e+03]
 [4.00000000e+00 2.08962887e+01 5.14013154e+01 1.01139552e+03]
 [5.00000000e+00 2.40469202e+01 5.70575139e+01 1.01316460e+03]
 [6.00000000e+00 2.01663930e+01 5.32933812e+01 1.01020737e+03]
 [7.00000000e+00 2.31485662e+01 5.46964379e+01 1.01106710e+03]
 [8.00000000e+00 2.23917308e+01 5.25855190e+01 1.00870548e+03]
 [9.00000000e+00 1.92856532e+01 5.17695182e+01 1.01205450e+03]]


: 

In [ ]:
# Temperature
temp_avg = np.mean(temperature)
temp_min = np.min(temperature)
temp_max = np.max(temperature)
temp_std = np.std(temperature)

#Humidity
hum_avg = np.mean(humidity)
hum_min = np.min(humidity)
hum_max = np.max(humidity)
hum_std = np.std(humidity)

#Pressure
press_avg = np.mean(pressure)
press_min = np.min(pressure)
press_max = np.max(pressure)
press_std = np.std(pressure)


print("Temperature average:", temp_avg)
print("Temperature minimum:", temp_min)
print("Temperature maximum:", temp_max)
print("Temperature standard deviation:", temp_std)

print ("___________________________________________________")

print("Humidity average:", hum_avg)
print("Humidity minimum:", hum_min)
print("Humidity maximum:", hum_max)
print("Humidity standard deviation:", hum_std)

print ("___________________________________________________")

print("Pressure average:", press_avg)
print("Pressure minimum:", press_min)
print("Pressure maximum:", press_max)
print("Pressure standard deviation:", press_std)


Temperature average: 21.984477635112263
Temperature minimum: 15.738172023629115
Temperature maximum: 28.68829841675688
Temperature standard deviation: 1.9794441854513787
___________________________________________________
Humidity average: 55.00430749036572
Humidity minimum: 39.80133445852525
Humidity maximum: 70.7346206415158
Humidity standard deviation: 4.801430635261065
___________________________________________________
Pressure average: 1011.8926520687038
Pressure minimum: 1001.8345118818972
Pressure maximum: 1022.0369518213569
Pressure standard deviation: 3.0167355232788013


In [ ]:
temp_per_hour = temperature.reshape(24, 60)
hum_per_hour = humidity.reshape(24, 60)
press_per_hour = pressure.reshape(24, 60)

temp_hour_avg = np.mean(temp_per_hour, axis=1)
hum_hour_avg = np.mean(hum_per_hour, axis=1)
press_hour_avg = np.mean(press_per_hour, axis=1)

print("\nTemperature hourly averages:", temp_hour_avg)
print("____________________________________________________________________")
print("\nHumidity hourly averages:", hum_hour_avg)
print("____________________________________________________________________")
print("\nPressure hourly averages:", press_hour_avg)


Temperature hourly averages: [22.14166268 22.13409179 22.51376313 21.92348889 21.41107237 22.04114242
 22.18399013 21.98587753 21.92227197 21.5687152  22.39897806 22.52648179
 22.02387316 21.72115601 21.61912546 22.46962628 21.95157416 21.81268957
 21.99589763 22.20357389 21.90688311 21.84429224 21.6040312  21.72320459]
____________________________________________________________________

Humidity hourly averages: [54.19372694 55.63239013 54.79775197 54.51592584 55.53295763 55.48627083
 55.25539843 54.53552143 55.09278221 54.03324649 54.86568163 54.89228243
 55.33769309 54.60026396 54.94205612 55.07499965 54.51339203 55.70155973
 54.79528374 56.19332656 54.7350799  54.61932811 55.35285142 55.40360951]
____________________________________________________________________

Pressure hourly averages: [1011.48501745 1011.53134669 1011.4035086  1011.56543685 1011.62894716
 1011.75148005 1011.95241716 1011.84212378 1012.02860946 1012.18676196
 1012.19988798 1011.58655104 1011.52654423 1012.12

In [ ]:
limit = 25

high_temp_count = np.sum(temperature > limit)
minute_of_min_temp = minutes[np.argmin(temperature)]

print("\nNumber of Minutes with temperature higher than", limit, ":", high_temp_count)
print("\nMinute when temperature was the lowest:", minute_of_min_temp)



Number of minutes with temperature higher than 25 : 79

Minute when temperature was the lowest: 294
