## Part 1: Array Creation and Properties

In [2]:
import numpy as np

1. Create a 1D array named arr1d with integers from 0 to 9.

In [3]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2. Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [4]:
arr2d = np.ones((3,3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [5]:
arr2d.ndim

2

3. Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [6]:
random_matrix = np.random.randn(3,3)
random_matrix

array([[ 2.22619932,  0.98067861, -0.21827186],
       [-1.11309359,  0.14377681,  0.88428971],
       [-1.34029573, -0.07671304, -0.55053947]])

4. Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [7]:
even_numbers = np.arange(10,51,2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

5. Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [8]:
linspace_array = np.linspace(0,1,7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

6. Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [9]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr.shape

(2, 3)

In [11]:
arr.ndim

2

In [12]:
arr.dtype

dtype('int32')

## Part 2: Array Manipulation

7. Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [14]:
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
reshaped_arr = arr1d.reshape(2,5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

8. Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [16]:
transposed_arr = np.transpose(reshaped_arr)
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

9. Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

10. Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [21]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
np.hstack((m1,m2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

11. Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [23]:
arr_to_split = np.arange(16).reshape(4, 4)
h_split = np.hsplit(arr_to_split,2)
for part in h_split:
    print(part)
    print("---")

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
---
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
---


12. Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [25]:
arr_to_split = np.arange(16).reshape(4, 4)
v_split= np.vsplit(arr_to_split,2)
print("vertical split by 2:\n", v_split[0], "\n---\n", v_split[1])

vertical split by 2:
 [[0 1 2 3]
 [4 5 6 7]] 
---
 [[ 8  9 10 11]
 [12 13 14 15]]


## Part 3: Indexing, Slicing, and Boolean Indexing

13. Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [28]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
data

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [30]:
data[0,1]

11

14. From the data array (from Q13), extract the first two rows and all columns.

In [31]:
data[:2,:]

array([[10, 11, 12],
       [13, 14, 15]])

15. From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [32]:
rows = [0,1,2]
columns = [1,2,1]
data[rows,columns]

array([11, 15, 17])

16. Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [34]:
scores = np.array([85, 92, 78, 65, 95, 88])
scores[scores>80]

array([85, 92, 95, 88])

## Part 4: Numerical Operations and Aggregations

17. Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [37]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
print("Multiplication:",arr_op1*arr_op2)
print("Division:",arr_op1/arr_op2)

Multiplication: [ 20  80 180]
Division: [5. 5. 5.]


18. Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [39]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Sum of all elements in the matrix:\n",np.sum(matrix))

Sum of all elements in the matrix:
 45


19. From the matrix (from Q18), calculate the mean of each column.

In [41]:
print("The mean of each column:\n",np.mean(matrix, axis=0))

The mean of each column:
 [4. 5. 6.]


20. Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [43]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discount_result = price_array * discount_percentage
discount_result

array([10., 15., 20., 25.])