## Scenario: You are a data scientist monitoring environmental conditions in a smart building. You have collected sensor data (temperature, humidity, pressure) over 24 hours, with readings taken every minute. Your goal is to process this raw data to find key statistics and identify anomalies.

#### 1. Data Generation:

Create a NumPy array for time_in_minutes from 0 to 1439 (24 hours * 60 minutes).

In [70]:
import numpy as np
import pandas as pd

In [31]:
time_in_minutes = np.arange(0,1440)
time_in_minutes

array([   0,    1,    2, ..., 1437, 1438, 1439])

Generate synthetic temperature data: a base temperature (e.g., 22°C) with some random fluctuations (use np.random.normal).

In [32]:
temperature = 22 + np.random.normal(loc=0, scale=1.0, size=1440)
temperature

array([20.73014501, 20.63794827, 21.41425212, ..., 22.2720221 ,
       22.97151664, 22.22399089])

Generate synthetic humidity data: a base humidity (e.g., 55%) with random fluctuations, ensuring values stay realistic (0-100%).

In [33]:
humidity = np.clip(55 + np.random.normal(loc=0, scale=10.0, size=1440), 0, 100)
humidity

array([68.04784144, 49.28301648, 59.96123155, ..., 46.73578262,
       49.81434704, 46.30558192])

Generate synthetic pressure data: a base pressure (e.g., 1012 hPa) with random fluctuations.

In [34]:
pressure = 1012 + np.random.normal(loc=0, scale=3.0, size=1440)
pressure

array([1008.55305909, 1008.7889085 , 1012.09056027, ..., 1010.21340861,
       1006.83639469, 1013.25220358])

Combine these into a single 2D NumPy array where each row represents a minute and columns are [time, temperature, humidity, pressure].

In [35]:
np.column_stack((time_in_minutes,temperature,humidity,pressure))

array([[0.00000000e+00, 2.07301450e+01, 6.80478414e+01, 1.00855306e+03],
       [1.00000000e+00, 2.06379483e+01, 4.92830165e+01, 1.00878891e+03],
       [2.00000000e+00, 2.14142521e+01, 5.99612315e+01, 1.01209056e+03],
       ...,
       [1.43700000e+03, 2.22720221e+01, 4.67357826e+01, 1.01021341e+03],
       [1.43800000e+03, 2.29715166e+01, 4.98143470e+01, 1.00683639e+03],
       [1.43900000e+03, 2.22239909e+01, 4.63055819e+01, 1.01325220e+03]])

In [36]:
data = np.column_stack((time_in_minutes, temperature, humidity, pressure))
data

array([[0.00000000e+00, 2.07301450e+01, 6.80478414e+01, 1.00855306e+03],
       [1.00000000e+00, 2.06379483e+01, 4.92830165e+01, 1.00878891e+03],
       [2.00000000e+00, 2.14142521e+01, 5.99612315e+01, 1.01209056e+03],
       ...,
       [1.43700000e+03, 2.22720221e+01, 4.67357826e+01, 1.01021341e+03],
       [1.43800000e+03, 2.29715166e+01, 4.98143470e+01, 1.00683639e+03],
       [1.43900000e+03, 2.22239909e+01, 4.63055819e+01, 1.01325220e+03]])

#### Basic Statistics: 

Calculate the average, minimum, maximum temperature, humidity, and pressure for the entire 24-hour period.

In [45]:
# temperature
print("average temperature:", np.mean(data[:,1]))
print("minimum temperature:",np.min(data[:,1]))
print("maximum temperature:",np.max(data[:,1]))

average temperature: 21.969698085465502
minimum temperature: 18.65243449633642
maximum temperature: 25.212331557533666


In [46]:
# humidity
print("average humidity:", np.mean(data[:,2]))
print("minimum humidity:",np.min(data[:,2]))
print("maximum humidity:",np.max(data[:,2]))

average humidity: 55.144202978225
minimum humidity: 19.827920981049417
maximum humidity: 85.57939198276216


In [47]:
# pressure
print("average pressure:", np.mean(data[:,3]))
print("minimum pressure:",np.min(data[:,3]))
print("maximum pressure:",np.max(data[:,3]))

average pressure: 1011.9665401045582
minimum pressure: 1001.4355412423142
maximum pressure: 1022.5331786661015


Find the standard deviation for each of these parameters.

In [53]:
print("standard deviation of temperature:\n",np.std(data[:, 1]))
print("standard deviation of humidity:\n",np.std(data[:, 2]))
print("standard deviation of pressure:\n",np.std(data[:, 3]))

standard deviation of temperature:
 0.9878862639950526
standard deviation of humidity:
 10.182299816029307
standard deviation of pressure:
 2.8692198491932124


#### Hourly Averages:

Reshape the data (or use slicing/aggregation) to calculate the average temperature, humidity, and pressure for each hour of the day. You should end up with 24 average values for each parameter.

In [56]:
reshaped_data = data.reshape(24, 60, 4)
hourly_avg_temp = reshaped_data[:, :, 1].mean(axis=1)
hourly_avg_humidity = reshaped_data[:, :, 2].mean(axis=1)
hourly_avg_pressure = reshaped_data[:, :, 3].mean(axis=1)
print("hourly average temperature:\n",hourly_avg_temp)
print("hourly average humidity:\n",hourly_avg_humidity)
print("hourly average pressure:\n",hourly_avg_pressure)

hourly average temperature:
 [21.96928895 22.24042578 21.90685665 21.86211784 21.9635614  21.90749031
 21.95219982 21.94415021 21.88742965 21.9611996  21.84002213 21.88040491
 21.81592031 22.04791096 21.83405343 22.09055645 22.0229497  22.09207015
 22.09896642 22.06423443 21.94292016 21.90966871 21.94690991 22.09144616]
hourly average humidity:
 [54.83005311 54.96473988 52.91740683 55.6597039  55.27064717 56.62878047
 55.9586929  54.77539729 56.98208593 54.57441327 55.75694369 54.8492504
 52.77533912 56.94711676 54.41427735 54.24342248 53.52050606 54.15945683
 56.79269721 56.25347032 55.7969432  55.90262543 54.34251438 55.14438751]
hourly average pressure:
 [1011.47887951 1011.73036832 1012.03266659 1012.27332065 1011.70065955
 1011.30807367 1012.1637931  1012.90173349 1012.08176549 1011.39491834
 1012.31888201 1011.89784087 1011.96728011 1011.22305846 1012.35428678
 1011.77691394 1011.83122068 1012.23681736 1012.14200634 1012.33972211
 1011.99109465 1011.91518554 1011.98472515 1012.15

#### Anomaly Detection (Simple):

Identify and count how many minutes the temperature exceeded a certain threshold (e.g., 25°C).

In [57]:
data[data[:,1]>25]

array([[ 327.        ,   25.21233156,   48.45552976, 1010.89456307]])

Find the time (in minutes) when the minimum temperature occurred.

In [62]:
np.min(data[:,1])

18.65243449633642

#### Data Export (Optional):

Save the combined 2D array to a .csv file using NumPy's saving functions.

In [75]:
np.savetxt('sensor_data.csv', data, delimiter=',')