In [14]:
! pip install numpy

In [1]:
import numpy as np

1.Create a 1D array named arr1d with integers from 0 to 9.

In [2]:
arr_id = np.arange(10)
arr_id

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

2.Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [3]:
arr2d = np.ones((3, 3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

3.Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [4]:
norm_arr=np.random.rand(3,3)
norm_arr

array([[0.922171  , 0.13000182, 0.71289686],
       [0.12874941, 0.03579324, 0.32935317],
       [0.97711262, 0.39871694, 0.42862618]])

4.Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [5]:
even_numbers= np.arange(10, 51, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

5.Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [6]:
space_arr=np.linspace(0,1,6)
space_arr

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

6.Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [9]:
list_id=[1,2,4],[4,5,6]
arr_id= np.array(list_id)
arr_id.dtype #data type

dtype('int64')

In [13]:
arr_id.shape #shape

(2, 3)

In [12]:
arr_id.ndim #dimensions

2

Part 2: Array Manipulation
1. Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [19]:
arr1d= np.arange(10)
reshaped_arr = arr1d.reshape(2, 5)
print("Reshaped 2*5 array:\n", reshaped_arr)

Reshaped 2*5 array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


2.Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [20]:
transposed_arr = reshaped_arr.T
print("\nTransposed array:\n", transposed_arr)


Transposed array:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


3.Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [24]:
arr_1 = np.array([1, 2, 3])
arr_2 = np.array([4, 5, 6])

v_stack = np.vstack((arr_1, arr_2))
print("Vertical stack of 1D arrays :\n", v_stack)

Vertical stack of 1D arrays :
 [[1 2 3]
 [4 5 6]]


4.Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [25]:
m1 = np.array([[1, 2] , [3,4]])
m2= np.array([[5,6] , [7,8]])

h_stack = np.hstack((m1, m2))
print("Horizontal stack of 2D arrays:\n", h_stack)

Horizontal stack of 2D arrays:
 [[1 2 5 6]
 [3 4 7 8]]


5.Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [26]:
arr_to_split = np.arange(16).reshape(4, 4)
h_split = np.hsplit(arr_to_split, 2)
print("\nHorizontal split into 2 parts:")
print("Part 1:\n", h_split[0])
print("Part 2:\n", h_split[1])


Horizontal split into 2 parts:
Part 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Part 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


6.Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [27]:
v_split = np.vsplit(arr_to_split, 2)
print("\nVertical split at row index 2:")
print("Top half:\n", v_split[0])
print("Bottom half:\n", v_split[1])


Vertical split at row index 2:
Top half:
 [[0 1 2 3]
 [4 5 6 7]]
Bottom half:
 [[ 8  9 10 11]
 [12 13 14 15]]


Part 3: Indexing, Slicing, and Boolean Indexing

1.Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [28]:
data = np.array([[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]])

# Extract element at row 1, column 2 (15)
element = data[1, 2]
print("Element at row 1, col 2:", element)

Element at row 1, col 2: 15


2.From the data array (from Q13), extract the first two rows and all columns.

In [29]:
# Extract first two rows, all columns
subarray = data[:2, :]
print("\nFirst two rows:\n", subarray)


First two rows:
 [[10 11 12]
 [13 14 15]]


3.From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [30]:
fancy = data[[0, 1, 2], [1, 2, 1]]  # (0,1), (1,2), (2,1)
print("\nFancy indexed elements (11, 15, 17):", fancy)


Fancy indexed elements (11, 15, 17): [11 15 17]


4.Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [31]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print("\nScores > 80:", high_scores)


Scores > 80: [85 92 95 88]


Part 4: Numerical Operations and Aggregations

1.Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [33]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])

product = arr_op1 * arr_op2
division = arr_op1 / arr_op2
print("\nElement-wise multiplication:", product)
print("Element-wise division:", division)


Element-wise multiplication: [ 20  80 180]
Element-wise division: [5. 5. 5.]


2.Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [37]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
total_sum = np.sum(matrix)
print("\nSum of all matrix elements:", total_sum)


Sum of all matrix elements: 45


3.From the matrix (from Q18), calculate the mean of each column.

In [36]:
column_means = np.mean(matrix, axis=0)
print("Mean of each column:", column_means)

Mean of each column: [4. 5. 6.]


4.Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [39]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discounted_prices = price_array * (1 - discount_percentage)
print("\nDiscounted prices:", discounted_prices)


Discounted prices: [ 90. 135. 180. 225.]
