In [3]:
import numpy as np

## part 1
#### 1-Create a 1D array named `arr1d` with integers from 0 to 9


In [4]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 2-reate a 2D array `arr2d` of shape (3, 3) filled with ones


In [5]:
arr2d = np.ones((3, 3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 3-Create a 3x3 array named `random_matrix` with random floating-point numbers from a standard normal distribution.

In [61]:
random_matrix = np.random.randn(3, 3)
random_matrix

array([[-0.04224131, -1.93263935, -0.92071576],
       [-1.49206887, -0.14189198, -0.38894167],
       [ 0.47334174,  0.17576281,  1.13003247]])

#### 4-Create an array named `even_numbers` containing even numbers from 10 to 50 (inclusive).


In [8]:
even_numbers= np.arange(10, 51, 2)
even_numbers 

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 5-Create an array named `linspace_array` containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [9]:
linspace_array =np.linspace(0, 1, 7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

####  6-arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(2, 3)
2
int64


## patr 2
#### 1-Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [30]:
reshape_array= arr1d.reshape(5,2)
reshape_array

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

#### 2-Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [31]:
transposed_arr= reshape_array.T
transposed_arr

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

#### 3-Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.


In [34]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vertical_a = np.vstack(a)
vertical_b = np.vstack(b)
print("vertical of a:\n", vertical_a)
print("\nvertical of b:\n", vertical_b)

vertical of a:
 [[1]
 [2]
 [3]]

vertical of b:
 [[4]
 [5]
 [6]]


#### 4- Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.


In [35]:
m1 = np.array([[1, 2], [3, 4]]) 
m2 = np.array([[5, 6], [7, 8]])

horizontally_m1 =np.hstack(m1)
horizontally_m2 =np.hstack(m2)
print("horizontally of m1:\n", horizontally_m1)
print("\nhorizontally of m2:\n", horizontally_m2)

horizontally of m1:
 [1 2 3 4]

horizontally of m2:
 [5 6 7 8]


#### 5-Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [59]:
array = np.arange(16).reshape(4, 4)
array_split = np.split(array, 2, axis=0)
print(array)
print("\nTHE ARRAY AFTER SPLIT IS (FIRIST 1) \n:",array_split)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

THE ARRAY AFTER SPLIT IS (FIRIST 1) 
: [array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])]


#### 6-Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.
 

In [55]:
print("\nTHE ARRAY AFTER SPLIT IS (FIRIST 1) \n:",array_split[0] ) 
print("\nTHE ARRAY AFTER SPLIT IS (SECOND 2)\n:",array_split[1] )


THE ARRAY AFTER SPLIT IS (FIRIST 1) 
: [[0 1 2 3]
 [4 5 6 7]]

THE ARRAY AFTER SPLIT IS (SECOND 2)
: [[ 8  9 10 11]
 [12 13 14 15]]


# Part 3:
#### Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [63]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
element = data[1, 2]
element

np.int64(15)

#### From the data array (from Q13), extract the first two rows and all columns.


In [66]:
find =data[:2,:]
find

array([[10, 11, 12],
       [13, 14, 15]])

#### 3-From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [67]:
elements = data[:3,1]
elements

array([11, 14, 17])

#### 4- Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [80]:
scores = np.array([85, 92, 78, 65, 95, 88])
find_num = scores>80
print("THE NUMBERS GREATER THAN 80 ARE:\n", find_num, "\n----------------------------------------")
greater_than_80 = scores[find_num]
print("Your numbers that are greater than 80 are:\n", greater_than_80)

THE NUMBERS GREATER THAN 80 ARE:
 [ True  True False False  True  True] 
----------------------------------------
[85 92 95 88]


# Part 4:
#### 1- Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [82]:
arr_op1 = np.array([10, 20, 30]) 
arr_op2 = np.array([2, 4, 6])

multiplication= arr_op1 * arr_op2
division = arr_op1 / arr_op2
print("Multiplication result:", multiplication)
print("Division result:", division)

Multiplication result: [ 20  80 180]
Division result: [5. 5. 5.]


#### 2- Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [85]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

calculate_sum = np.sum(matrix) 
print("The resulte of sum is:\n ", calculate_sum)

The resulte of sum is:
  45


#### 3-From the matrix (from Q18), calculate the mean of each column.

In [88]:
calculate_mean= np.mean(matrix, axis=0)
print("The Mean of Each Column Is:\n", calculate_mean)

The Mean of each column Is:
 [4. 5. 6.]


#### 4-Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [92]:
price_array = np.array([100, 150, 200, 250])

discount_percentage = 0.10
resulte = price_array * discount_percentage

price_after_discount = price_array - resulte
print("The Price Will Be After Discount:\n",price_after_discount)

The Price Will Be After Discount:
 [ 90. 135. 180. 225.]
