In [1]:
import numpy as np

In [8]:
# Data Generation
np.random.seed(42)
time_in_minutes = np.arange(0, 24 * 60)
temperature = 22 + np.random.normal(0, 1.5, size=time_in_minutes.shape)
humidity = 55 + np.random.normal(0, 10, size=time_in_minutes.shape)
humidity = np.clip(humidity, 0, 100)
pressure = 1012 + np.random.normal(0, 3, size=time_in_minutes.shape)
sensor_data = np.column_stack((time_in_minutes, temperature, humidity, pressure))


print("Sample data (first 5 rows):\n", sensor_data[:5])



Sample data (first 5 rows):
 [[0.00000000e+00 2.27450712e+01 6.16288127e+01 1.00528531e+03]
 [1.00000000e+00 2.17926035e+01 6.67347386e+01 1.00563790e+03]
 [2.00000000e+00 2.29715328e+01 5.68102156e+01 1.01017940e+03]
 [3.00000000e+00 2.42845448e+01 4.20316805e+01 1.01337306e+03]
 [4.00000000e+00 2.16487699e+01 5.89968795e+01 1.00375749e+03]]


In [9]:
#Statistics
avg_temp = np.mean(temperature)
min_temp = np.min(temperature)
max_temp = np.max(temperature)
std_temp = np.std(temperature)

avg_humidity = np.mean(humidity)
min_humidity = np.min(humidity)
max_humidity = np.max(humidity)
std_humidity = np.std(humidity)

avg_pressure = np.mean(pressure)
min_pressure = np.min(pressure)
max_pressure = np.max(pressure)
std_pressure = np.std(pressure)

print(f"Temperature: Avg = {avg_temp:.2f}, Min = {min_temp:.2f}, Max = {max_temp:.2f}, Std = {std_temp:.2f}")
print(f"Humidity:    Avg = {avg_humidity:.2f}, Min = {min_humidity:.2f}, Max = {max_humidity:.2f}, Std = {std_humidity:.2f}")
print(f"Pressure:    Avg = {avg_pressure:.2f}, Min = {min_pressure:.2f}, Max = {max_pressure:.2f}, Std = {std_pressure:.2f}")


Temperature: Avg = 22.06, Min = 17.14, Max = 27.78, Std = 1.48
Humidity:    Avg = 55.27, Min = 24.80, Max = 86.93, Std = 9.77
Pressure:    Avg = 1011.89, Min = 1002.98, Max = 1023.78, Std = 3.08


In [10]:
#Hourly Averages
temperature_hourly = temperature.reshape(24, 60)
humidity_hourly = humidity.reshape(24, 60)
pressure_hourly = pressure.reshape(24, 60)

# Compute hourly averages
avg_temp_hourly = np.mean(temperature_hourly, axis=1)
avg_humidity_hourly = np.mean(humidity_hourly, axis=1)
avg_pressure_hourly = np.mean(pressure_hourly, axis=1)

print("Hourly Average Temperature:\n", avg_temp_hourly)
print("Hourly Average Humidity:\n", avg_humidity_hourly)
print("Hourly Average Pressure:\n", avg_pressure_hourly)


Hourly Average Temperature:
 [21.76801798 21.99447486 22.13787138 22.08522141 21.97280018 22.05649559
 22.19270336 21.99189762 21.59898083 21.99874773 22.14703561 21.87394689
 21.99035223 22.13255649 22.47256467 22.14220817 22.14433964 22.09980311
 22.41754739 21.93390133 22.04927415 22.06195067 21.79311885 22.3785818 ]
Hourly Average Humidity:
 [57.69977381 55.00100071 53.7400147  57.3080651  56.2335408  54.85853065
 54.19651501 54.85200737 56.0027414  54.55652575 54.1566468  54.68346916
 55.48323442 54.17266086 57.29077742 52.80865337 55.60522042 55.60899535
 55.99786874 55.88059912 54.45618991 57.79781197 53.51920764 54.46443214]
Hourly Average Pressure:
 [1012.0482827  1011.970714   1011.21972561 1012.24099963 1011.12138271
 1012.31426335 1012.28217864 1012.34027712 1012.04352739 1012.12893804
 1011.854483   1012.44200617 1011.87495132 1012.78019974 1011.22934488
 1011.20064011 1011.66378213 1012.18013824 1011.76792849 1011.75179853
 1012.32850614 1011.49985397 1011.67230703 1011.3

In [11]:
#Anomaly Detection

threshold_temp = 25
high_temp_minutes = temperature > threshold_temp
num_high_temp = np.sum(high_temp_minutes)

min_temp_time = time_in_minutes[np.argmin(temperature)]

print(f"Number of minutes temperature exceeded {threshold_temp}°C:", num_high_temp)
print("Time (minute) when minimum temperature occurred:", min_temp_time)



Number of minutes temperature exceeded 25°C: 41
Time (minute) when minimum temperature occurred: 262


In [12]:

# Save data to CSV
np.savetxt("sensor_data.csv", sensor_data, delimiter=",", 
           header="time_min,temperature,humidity,pressure", comments='', fmt="%.2f")
print("Data saved to sensor_data.csv")


Data saved to sensor_data.csv
