## part 1

In [4]:
import numpy as np 

In [7]:
list_1d=[1, 2 ,3 ,4]
arr_1d= np.array(list_1d)

type (arr_1d)

numpy.ndarray

In [9]:
arr_1d.ndim

1

In [10]:
zeros_arr = np.zeros((6,3))
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [12]:
ones_arr = np.ones((3 ,3,2))
ones_arr

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [16]:
full_arr = np.full((3,2),5)
full_arr

array([[5, 5],
       [5, 5],
       [5, 5]])

In [26]:
space_arr= np.linspace(0,1,7)
space_arr

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

In [ ]:
rand_arr= np.random.rand(3,2)
rand

In [19]:
arr1d= np.arange(0,10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
ones_arr= np.ones((3,3))
ones_arr

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
random_matrix= np.random.rand (3,3)
random_matrix

array([[0.07325721, 0.70768233, 0.18048614],
       [0.21308752, 0.186929  , 0.59036684],
       [0.53875142, 0.96019189, 0.07494783]])

In [23]:
even_number= np.arange(10,51,2)
even_number

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [27]:
arr= np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [28]:
arr.shape

(2, 3)

In [29]:
arr.ndim

2

In [30]:
arr.dtype

dtype('int64')

In [32]:
type(arr)

numpy.ndarray

## part2  

In [1]:
import numpy as np


arr1d = np.arange(10)  
reshaped_arr = arr1d.reshape(2, 5)
print("Reshaped (2x5) Array:\n", reshaped_arr)

Reshaped (2x5) Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [2]:
transposed_arr = reshaped_arr.T
print("\nTransposed Array:\n", transposed_arr)



Transposed Array:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]


In [3]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_vertical = np.vstack((a, b))
print("\nVertically Stacked 1D Arrays:\n", stacked_vertical)



Vertically Stacked 1D Arrays:
 [[1 2 3]
 [4 5 6]]


In [4]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
stacked_horizontal = np.hstack((m1, m2))
print("\nHorizontally Stacked 2D Arrays:\n", stacked_horizontal)


Horizontally Stacked 2D Arrays:
 [[1 2 5 6]
 [3 4 7 8]]


In [5]:
arr_to_split = np.arange(16).reshape(4, 4)
split_horizontal = np.hsplit(arr_to_split, 2)
print("\nHorizontally Split Arrays:")
for i, part in enumerate(split_horizontal, 1):
    print(f"Part {i}:\n", part)


Horizontally Split Arrays:
Part 1:
 [[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
Part 2:
 [[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [6]:
split_vertical = np.vsplit(arr_to_split, 2)
print("\nVertically Split Arrays:")
for i, part in enumerate(split_vertical, 1):
    print(f"Part {i}:\n", part)


Vertically Split Arrays:
Part 1:
 [[0 1 2 3]
 [4 5 6 7]]
Part 2:
 [[ 8  9 10 11]
 [12 13 14 15]]


## part 3

In [7]:
import numpy as np


arr1d = np.arange(10)


reshaped_arr = arr1d.reshape(2, 5)
print("Reshaped Array:\n", reshaped_arr)

Reshaped Array:
 [[0 1 2 3 4]
 [5 6 7 8 9]]


In [8]:
transposed_arr = reshaped_arr.T
print("\nTransposed Array:\n", transposed_arr)


a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
v_stack = np.vstack((a, b))
print("\nVertical Stack:\n", v_stack)


m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
h_stack = np.hstack((m1, m2))
print("\nHorizontal Stack:\n", h_stack)




Transposed Array:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]]

Vertical Stack:
 [[1 2 3]
 [4 5 6]]

Horizontal Stack:
 [[1 2 5 6]
 [3 4 7 8]]


In [9]:

arr_to_split = np.arange(16).reshape(4, 4)
split_h = np.hsplit(arr_to_split, 2)
print("\nHorizontal Split:")
for part in split_h:
    print(part)


split_v = np.vsplit(arr_to_split, 2)
print("\nVertical Split:")
for part in split_v:
    print(part)


Horizontal Split:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]

Vertical Split:
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


## part 4

In [10]:
import numpy as np


arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])

multiplication = arr_op1 * arr_op2
division = arr_op1 / arr_op2

print("Element-wise Multiplication:\n", multiplication)
print("Element-wise Division:\n", division)


Element-wise Multiplication:
 [ 20  80 180]
Element-wise Division:
 [5. 5. 5.]


In [11]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

total_sum = np.sum(matrix)
print("\nSum of all elements in matrix:", total_sum)



Sum of all elements in matrix: 45


In [12]:
column_mean = np.mean(matrix, axis=0)
print("Mean of each column:", column_mean)

Mean of each column: [4. 5. 6.]


In [13]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10

discounted_prices = price_array * (1 - discount_percentage)
print("Discounted Prices:", discounted_prices)

Discounted Prices: [ 90. 135. 180. 225.]
