## Task Scenario:
You are a junior data analyst at an online retail company. Your manager wants to understand daily sales patterns. You need to simulate a month's worth of sales data and then use NumPy to extract insights about sales performance.

In [9]:
import numpy as np

## Sales Data Generation: 

In [11]:
np.random.seed(42)

base_revenue = 1000
revenue_fluctuations = np.random.normal(loc=0, scale=200, size=30)
raw_revenue = base_revenue + revenue_fluctuations
sales_revenue = np.where(raw_revenue < 0, 0, raw_revenue)

raw_revenue
sales_revenue



array([1099.3428306 ,  972.34713977, 1129.53770762, 1304.60597128,
        953.16932506,  953.17260861, 1315.8425631 , 1153.48694583,
        906.10512281, 1108.51200872,  907.31646144,  906.85404929,
       1048.39245431,  617.34395107,  655.0164335 ,  887.54249415,
        797.43377593, 1062.84946652,  818.3951849 ,  717.53925973,
       1293.12975378,  954.8447399 , 1013.50564094,  715.05036276,
        891.12345509, 1022.18451794,  769.80128452, 1075.13960367,
        879.87226202,  941.66125004])

In [13]:
# 1.2 Simulate units sold
base_units = 50
units_with_noise = (sales_revenue / base_revenue) * base_units + np.random.normal(0, 5, 30)
units_sold = np.where(units_with_noise < 0, 0, units_with_noise)
sales_revenue = sales_revenue.round(2)
units_sold = units_sold.round(0)

sales_revenue

array([1099.34,  972.35, 1129.54, 1304.61,  953.17,  953.17, 1315.84,
       1153.49,  906.11, 1108.51,  907.32,  906.85, 1048.39,  617.34,
        655.02,  887.54,  797.43, 1062.85,  818.4 ,  717.54, 1293.13,
        954.84, 1013.51,  715.05,  891.12, 1022.18,  769.8 , 1075.14,
        879.87,  941.66])

# Step 2: Combine Data

In [14]:

sales_data = np.column_stack((sales_revenue, units_sold))
sales_data

array([[1099.34,   53.  ],
       [ 972.35,   48.  ],
       [1129.54,   51.  ],
       [1304.61,   59.  ],
       [ 953.17,   52.  ],
       [ 953.17,   54.  ],
       [1315.84,   65.  ],
       [1153.49,   63.  ],
       [ 906.11,   47.  ],
       [1108.51,   52.  ],
       [ 907.32,   47.  ],
       [ 906.85,   53.  ],
       [1048.39,   52.  ],
       [ 617.34,   39.  ],
       [ 655.02,   20.  ],
       [ 887.54,   48.  ],
       [ 797.43,   40.  ],
       [1062.85,   52.  ],
       [ 818.4 ,   41.  ],
       [ 717.54,   26.  ],
       [1293.13,   64.  ],
       [ 954.84,   50.  ],
       [1013.51,   58.  ],
       [ 715.05,   33.  ],
       [ 891.12,   41.  ],
       [1022.18,   49.  ],
       [ 769.8 ,   43.  ],
       [1075.14,   55.  ],
       [ 879.87,   41.  ],
       [ 941.66,   50.  ]])

# Step 3: KPIs

In [22]:
total_revenue = np.sum(sales_revenue)

total_revenue 


np.float64(28871.109999999997)

In [18]:
avg_units_per_day = np.mean(units_sold)
avg_units_per_day

np.float64(48.2)

In [19]:
max_revenue = np.max(sales_revenue)
max_revenue 


np.float64(1315.84)

In [20]:
day_of_max = np.argmax(sales_revenue) + 1  # +1 for 1-based index
day_of_max

np.int64(7)

In [21]:
avg_revenue_per_unit = total_revenue / np.sum(units_sold)
avg_revenue_per_unit


np.float64(19.96618948824343)

# Step 4: Conditional Analysis

## Identify and count how many days had sales_revenue above a certain target (e.g., $1200).

In [23]:

high_sales_days = sales_revenue > 1200
count_high_sales_days = np.sum(high_sales_days)

count_high_sales_days

np.int64(3)

## Calculate the average units_sold only for days when sales_revenue was below a certain threshold (e.g., $900).

In [24]:
low_sales_days = sales_revenue < 900
avg_units_low_revenue = np.mean(units_sold[low_sales_days])
avg_units_low_revenue

np.float64(37.2)

# Step 5: Weekly Aggregation (Days 1-28)

In [25]:

weekly_revenue = [
    np.sum(sales_revenue[0:7]),
    np.sum(sales_revenue[7:14]),
    np.sum(sales_revenue[14:21]),
    np.sum(sales_revenue[21:28])
]

weekly_revenue

[np.float64(7728.02),
 np.float64(6648.01),
 np.float64(6231.91),
 np.float64(6441.64)]