# Part 1: Array Creation and Properties

In [2]:
import numpy as np

### 1. Create a 1D array named arr1d with integers from 0 to 9:

In [3]:
arr1d = np.array([0, 1, 2, 3, 4,5, 6, 7, 8, 9])
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2. Create a 2D array named arr2d with shape (3, 3) filled with ones:

In [4]:
arr2d = np.ones((2, 3, 3))
arr2d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

### 3. Create a 3x3 array named random_matrix with random floating-point numbers from a stan5dard normal distribution:

In [5]:
random_matrix = np.random.randn(3, 3)
random_matrix

array([[ 0.26059422, -1.61429213, -0.60979001],
       [ 2.08817374,  0.03146409,  0.28037675],
       [-1.37001448, -1.29814192,  0.86823008]])

### 4. Create an array named even_numbers containing even numbers from 10 to 50 (inclusive):

In [6]:
even_numbers = np.arange(10, 51, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

### 5. Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive):

In [7]:
linspace_array = np.linspace(0, 1, 7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

### 6. Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them:

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(2, 3)
2
int64


# Part 2: Array Manipulation

### 7. Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr:

In [9]:
reshaped_arr = arr1d.reshape(2, 5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 8. Transpose reshaped_arr (from Q7). Name the result transposed_arr:

In [10]:
transposed_arr = reshaped_arr.T
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### 9. Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically:

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
v_stack = np.vstack((a,b))
v_stack

array([[1, 2, 3],
       [4, 5, 6]])

### 10. Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally:

In [12]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
h_stack = np.hstack((m1, m2))
h_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

### 11. Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts:

In [13]:
arr_to_split = np.arange(16).reshape(4, 4)
print(arr_to_split)
print("------------")
splited_arr_top = arr_to_split[:2, :]
print(splited_arr_top)
splited_arr_down = arr_to_split[2:, :]
print(splited_arr_down)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
------------
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


### 12. Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts:

In [15]:
arr_to_split = np.arange(16).reshape(4, 4)
splited_arr_left = arr_to_split[:, :2]
print(splited_arr_left)
splited_arr_right = arr_to_split[:, 2:]
print(splited_arr_right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


# Part 3: Indexing, Slicing, and Boolean Indexing

### 13. Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2:

In [18]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(data[1, -1])

15


### 14. From the data array (from Q13), extract the first two rows and all columns:

In [19]:
print(data[0 : 2, :])

[[10 11 12]
 [13 14 15]]


### 15. From the data array (from Q13), extract the elements 11, 15, and 17 using fancy From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns). (hint: you'll need to specify rows and columns):

In [26]:
# print(data[0, 1])
# print(data[1, -1])
# print(data[2, -2])
row = [0, 1, 2]
col = [1, -1, -2]
print(data[row, col])

[11 15 17]


### 16. Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80:

In [27]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
print(high_scores)

[85 92 95 88]


# Part 4: Numerical Operations and Aggregations

### 16. Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2):

In [29]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
result = arr_op1 * arr_op2
print(result)

[ 20  80 180]


### 17. Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix:

In [30]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sum = np.sum(matrix)
print(sum)

45


### 18. From the matrix (from Q17), calculate the mean of each column:

In [33]:
columns_mean = np.mean(matrix, axis=0)
print(columns_mean)

[4. 5. 6.]


### 19. Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting:

In [43]:
price_array = np.array([100, 150, 200, 250])
discount = 0.90
result = price_array * discount
print(result)

[ 90. 135. 180. 225.]
