In [73]:
import numpy as np

# Smart Building

### Scenario: You are a data scientist monitoring environmental conditions in a smart building. You have collected sensor data (temperature, humidity, pressure) over 24 hours, with readings taken every minute. Your goal is to process this raw data to find key statistics and identify anomalies.

## Data Generation:

### 1. Create a NumPy array for time_in_minutes from 0 to 1439 (24 hours * 60 minutes):

In [74]:
time_in_minutes = np.arange(0, 1440)
time_in_minutes

array([   0,    1,    2, ..., 1437, 1438, 1439], shape=(1440,))

### 2. Generate synthetic temperature data: a base temperature (e.g., 22°C) with some random fluctuations (use np.random.normal):

In [75]:
temp = np.random.normal(loc = 22, scale = 2, size = 100)
temp

array([24.18732055, 20.71824183, 21.60093047, 19.98247995, 21.72704046,
       21.4358903 , 20.74722823, 24.7176539 , 19.2966056 , 22.35426803,
       20.49773341, 22.17527615, 21.66288088, 23.42530955, 23.26893495,
       21.25866604, 19.53551393, 20.64307504, 22.86527847, 20.52950344,
       24.42798608, 23.33505744, 26.07899422, 20.4692392 , 21.46442175,
       23.88541725, 21.38274105, 24.15598382, 19.49595577, 23.41540932,
       22.9344427 , 24.97290037, 19.13476363, 25.82739001, 20.01964401,
       25.60407972, 21.44947758, 21.44835136, 20.05196859, 20.90147185,
       20.26366865, 22.52961243, 19.50197327, 21.3976327 , 23.69987754,
       23.8135083 , 25.21957362, 20.94642548, 18.67921562, 21.12025972,
       23.09674   , 25.60990367, 19.79200563, 24.26508059, 24.68501018,
       23.05239578, 21.53411798, 21.91143028, 21.48676286, 23.26867104,
       19.18896978, 24.67470186, 20.60396769, 25.86832014, 23.70657165,
       20.88155368, 23.66540495, 20.09383283, 24.60876139, 22.54

### 3. Generate synthetic humidity data: a base humidity (e.g., 55%) with random fluctuations, ensuring values stay realistic (0-100%):

In [76]:
hum = np.random.normal(loc = 55, scale = 2, size = 100)
hum = np.clip(hum, 0, 100) #Used to make the values between 0 to 100
hum

array([53.04152227, 57.46070632, 56.66297438, 57.64652561, 57.37428961,
       54.95374639, 53.63487872, 54.03017946, 57.33876638, 53.84295174,
       53.68345517, 54.59241097, 53.60622408, 57.59158825, 54.30616353,
       52.64632732, 56.35865265, 57.1913626 , 53.9004623 , 56.95699461,
       54.84824664, 56.3721414 , 53.78895777, 52.54239824, 54.38289146,
       55.17812331, 54.99942179, 58.03888288, 53.85596189, 56.09968328,
       55.5280573 , 57.26567139, 53.99270028, 56.89566898, 53.90326602,
       56.09098516, 56.43566811, 53.55701745, 52.54254162, 55.44043651,
       55.19995705, 54.50187721, 57.80674639, 56.17676514, 58.17496881,
       51.23654083, 55.30359353, 54.53150799, 55.39226072, 57.37990793,
       57.60796984, 52.36712957, 54.14945098, 57.03223116, 54.76342441,
       58.61203394, 57.21482668, 53.0110522 , 54.324598  , 54.66609596,
       53.78437492, 55.9146119 , 54.36055518, 57.68342633, 55.5278889 ,
       56.98283279, 52.08941085, 58.45533352, 55.85675953, 54.04

### 4. Generate synthetic pressure data: a base pressure (e.g., 1012 hPa) with random fluctuations:

In [77]:
pressure = np.random.normal(loc = 1012, scale = 2, size = 100)
pressure = np.clip(pressure, 980, 1050)
pressure

array([1010.60024061, 1013.87860859, 1011.09087305, 1013.73327374,
       1007.94406291, 1010.13642274, 1017.78678286, 1009.62996603,
       1009.71521473, 1016.2579821 , 1015.61004476, 1015.77859857,
       1012.51584076, 1014.39632306, 1015.91339905, 1011.29800215,
       1011.41477815, 1010.03189643, 1012.61967813, 1009.58158882,
       1013.93225199, 1009.72977512, 1010.57904577, 1010.73620808,
       1012.698099  , 1010.68937483, 1008.34694811, 1010.33179942,
       1013.79556244, 1015.31560066, 1010.72686297, 1009.80517695,
       1012.92474653, 1013.84516957, 1012.00943178, 1013.82329486,
       1014.07861385, 1010.24722658, 1015.05578554, 1013.26597505,
       1012.27004189, 1010.57009172, 1016.06179334, 1015.24401778,
       1011.43463809, 1010.51070464, 1012.8360355 , 1014.03686099,
       1011.62098338, 1012.43600155, 1013.5204009 , 1013.47354741,
       1011.68216904, 1011.89296164, 1009.69882989, 1010.17975138,
       1010.03504439, 1009.66495618, 1009.94051955, 1010.81386

### 5. Combine these into a single 2D NumPy array where each row represents a minute and columns are [time, temperature, humidity, pressure]:

In [78]:
time_in_minutes = np.arange(1440)
temp = np.random.normal(loc=22, scale=2, size=1440)
hum = np.clip(np.random.normal(loc=55, scale=5, size=1440), 0, 100)
pressure = np.clip(np.random.normal(loc=1012, scale=2, size=1440), 980, 1050)

table = np.column_stack((time_in_minutes, temp, hum, pressure))
print(table[:5])

[[0.00000000e+00 2.02161262e+01 5.39122867e+01 1.00863152e+03]
 [1.00000000e+00 2.19028629e+01 5.36610936e+01 1.01308687e+03]
 [2.00000000e+00 1.96093077e+01 5.20326338e+01 1.01372872e+03]
 [3.00000000e+00 2.41606963e+01 5.81769091e+01 1.01182782e+03]
 [4.00000000e+00 2.22403989e+01 5.54124299e+01 1.01100893e+03]]


## Basic Statistics

### 6. Calculate the average, minimum, maximum for temperature, humidity, and pressure for the entire 24-hour period:

In [79]:
avg_temp = np.mean(table[:, 1])
min_temp = np.min(table[:, 1])
max_temp = np.max(table[:, 1])

avg_hum = np.mean(table[:, 2])
min_hum = np.min(table[:, 2])
max_hum = np.max(table[:, 2])

# Pressure statistics
avg_pressure = np.mean(table[:, 3])
min_pressure = np.min(table[:, 3])
max_pressure= np.max(table[:, 3])

print(f"Temperature: \nAvg: {avg_temp:.2f}, \nMin: {min_temp:.2f}, \nMax: {max_temp:.2f}")
print("---------------|")
print(f"Humidity: \nAvg: {avg_hum:.2f}, \nMin: {min_hum:.2f}, \nMax: {max_hum:.2f}")
print("---------------|")
print(f"Pressure: \nAvg: {avg_pressure:.2f}, \nMin: {min_pressure:.2f}, \nMax: {max_pressure:.2f}")


Temperature: 
Avg: 21.94, 
Min: 15.83, 
Max: 30.16
---------------|
Humidity: 
Avg: 55.30, 
Min: 38.00, 
Max: 74.97
---------------|
Pressure: 
Avg: 1012.03, 
Min: 1006.13, 
Max: 1017.92


### 7. Find the standard deviation for each of these parameters:

In [80]:
std_temp = np.std(temp)
std_hum = np.std(hum)
std_pressure = np.std(pressure)

print(f"The Standard Deviation of the Tempreture is: {std_temp:.2f}")
print(f"The Standard Deviation of the Humidity is: {std_hum:.2f}")
print(f"The Standard Deviation of the Pressure is: {std_pressure:.2f}")

The Standard Deviation of the Tempreture is: 2.00
The Standard Deviation of the Humidity is: 5.01
The Standard Deviation of the Pressure is: 2.02


## Hourly Averages:

### 8. Reshape the data (or use slicing/aggregation) to calculate the average temperature, humidity, and pressure for each hour of the day. You should end up with 24 average values for each parameter:

In [81]:
temp_per_hour = temp.reshape(24, 60)
hum_per_hour = hum.reshape(24,60)
pressure_per_hour = pressure.reshape(24,60)

avg_temp_per_hour = np.mean(temp_per_hour, axis=1)
avg_hum_per_hour = np.mean(hum_per_hour, axis=1)
avg_pressure_per_hour = np.mean(pressure_per_hour, axis=1)

print(avg_temp_per_hour)
print("---------------|")
print(avg_hum_per_hour)
print("---------------|")
print(avg_pressure_per_hour)

[21.72186061 21.64479725 21.44975158 22.13425118 21.88986944 21.70561309
 21.87060337 22.3307755  22.17338513 21.93550124 22.17950884 21.85050895
 22.3299987  21.79090436 21.94075235 21.8660899  22.1460769  22.11465675
 21.98618117 21.88710621 21.8380579  22.28227181 21.71084374 21.88175311]
---------------|
[54.95380322 55.07488803 56.20394583 55.48966519 55.2571736  56.16404093
 53.83403869 55.10003631 54.83430053 55.26825696 55.28866096 54.96579708
 55.81670824 55.52964225 55.36175591 55.53037797 55.47921664 54.7850252
 55.66415118 56.0638677  53.94278591 54.70095181 55.84608189 56.12813855]
---------------|
[1012.06770914 1012.079358   1011.62399198 1011.81480437 1012.02696662
 1011.89355138 1012.32754087 1011.92672288 1012.04404903 1011.67287209
 1011.73005608 1012.56848374 1012.49975436 1012.18336914 1011.97924338
 1012.31181964 1012.23229889 1012.10795097 1012.2442683  1011.73033311
 1011.75296586 1012.28783348 1011.75602123 1011.91744696]


## Anomaly Detection (Simple):

### 9. Identify and count how many minutes the temperature exceeded a certain threshold (e.g., 25°C):

In [82]:
temperature_exceeded = temp > 25
count_temperature_exceeded = np.sum(temperature_exceeded)
print(f"The Minuts of the Temprature that Exceeded are: {count_temperature_exceeded}.")

The Minuts of the Temprature that Exceeded are: 88.


### 10. Find the time (in minutes) when the minimum temperature occurred:

In [83]:
min_temp_index = np.argmin(temp)
min_temp_time = table[min_temp_index, 0]
print(f"The Minimum Temperature Occurred at Minute: {int(min_temp_time)}")

The Minimum Temperature Occurred at Minute: 1433
