## Numpy Practise_Part 2

### Part 2: Array Manipulation

#### Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [1]:
import numpy as np

In [2]:
range_arr1d=np.arange(0,10)
reshaped_arr=range_arr1d.reshape(2,5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [4]:
transposed_arr=reshaped_arr.T
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

#### Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [5]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
v_stack = np.vstack((a,b))
print("Vertical stack:\n", v_stack)

Vertical stack:
 [[1 2 3]
 [4 5 6]]


#### Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [6]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
h_stack = np.hstack((m1, m2))
print("Horizontal stack:\n", h_stack)

Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]


#### Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [7]:
arr_to_split = np.arange(16).reshape(4, 4)
# Horizontal split into 2 parts (splits columns)
h_split = np.hsplit(arr_to_split, 2)
print("Horizontal split by 2:")
for part in h_split:
    print(part)
    print("---")

Horizontal split by 2:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
---
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
---


#### Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [9]:
arr_to_split = np.arange(16).reshape(4, 4)
# Vertical split into 2 parts (splits rows)
v_split = np.vsplit(arr_to_split, 2)
print("Vertical split by 2:\n", v_split[0], "\n--\n", v_split[1])

Vertical split by 2:
 [[0 1 2 3]
 [4 5 6 7]] 
--
 [[ 8  9 10 11]
 [12 13 14 15]]


## Part 3: Indexing, Slicing, and Boolean Indexing

#### Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [11]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
data[:,1:2]

array([[11],
       [14],
       [17]])

#### From the data array (from Q13), extract the first two rows and all columns.

In [13]:
data[:, 2:]

array([[12],
       [15],
       [18]])

#### From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [16]:
rows = [0, 1, 2]
cols = [1, 2, 1]

result = data[rows, cols]
result

array([11, 15, 17])

#### Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [17]:
scores = np.array([85, 92, 78, 65, 95, 88])
scores[scores>80]

array([85, 92, 95, 88])

## Part 4: Numerical Operations and Aggregations

#### Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [18]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
print("Multiplication:  ", arr_op1 * arr_op2)       
print("Division:        ", arr_op1 / arr_op2)       

Multiplication:   [ 20  80 180]
Division:         [5. 5. 5.]


#### Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.
 

In [19]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
total_sum = matrix.sum()
total_sum

np.int64(45)

#### From the matrix (from Q18), calculate the mean of each column.

In [20]:
column_means = np.mean(matrix, axis=0)
column_means

array([4., 5., 6.])

#### Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [21]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discount_price= price_array*(1-discount_percentage)
discount_price

array([ 90., 135., 180., 225.])