## Numpy Practise_Part 1

### Part 1: Array Creation and Properties

#### Create a 1D array named arr1d with integers from 0 to 9.

In [3]:
import numpy as np

In [4]:
range_arr1d=np.arange(0,10)
range_arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create a 2D array named arr2d with shape (3, 3) filled with ones.
 

In [6]:
ones_arr2d=np.ones((3,3))
ones_arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [7]:
random_matrix=np.random.rand(3,3)
random_matrix

array([[0.32079659, 0.89670057, 0.93731689],
       [0.39809845, 0.30261541, 0.43358861],
       [0.16769146, 0.74830517, 0.97959269]])

#### Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [9]:
even_numbers_arr=np.arange(10,51,2)
even_numbers_arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [10]:
linspace_array=np.linspace(0,1,7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

#### Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.shape

(2, 3)

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr.dtype

dtype('int64')