Import NumPy as np at the beginning of your script: import numpy as np
 
For each question, write the Python code that solves it.
 
Put the question in a Markdown cell and the Python code in a code cell.
 
Print the result for each question to verify your answer.

# Part 1: Array Creation and Properties

In [23]:
import numpy as np
from numpy import random

##### 1. Create a 1D array named arr1d with integers from 0 to 9.


In [24]:
arr1d = np.arange(10)
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 2. Create a 2D array named arr2d with shape (3, 3) filled with ones.


In [25]:
arr2d = np.ones((3,3))
arr2d

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

##### 3. Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [26]:
random_matrix = random.rand(3,3)
print("array shape:",random_matrix.shape)
random_matrix

array shape: (3, 3)


array([[0.32756185, 0.47665195, 0.60414043],
       [0.52891201, 0.70643682, 0.15289793],
       [0.44310286, 0.97294696, 0.23178402]])

##### 4. Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [27]:
even_numbers = np.arange(10, 51, 2)
even_numbers

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

##### 5. Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [28]:
linspace_array = np.linspace(0, 1, 7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

##### 6. Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.


In [29]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape :",arr.shape)
print("dimension :",arr.ndim)
print("type :",arr.dtype)

shape : (2, 3)
dimension : 2
type : int64


# Part 2: Array Manipulation

##### 1. Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [30]:
reshaped_arr = arr1d.reshape(2,5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### 2. Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [31]:
transposed_arr = reshaped_arr.T
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

##### 3. Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [32]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
vertical_stack = np.vstack((a,b))
vertical_stack

array([[1, 2, 3],
       [4, 5, 6]])

##### 4. Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.
 

In [33]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
horizontal_stack = np.hstack((m1,m2))
horizontal_stack

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

##### 5. Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [34]:
arr_to_split = np.arange(16).reshape(4, 4)
h1_split = np.hsplit(arr_to_split,2)
h1_split[0]
h1_split[1]

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

##### 6. Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [35]:
split_vertical = np.vsplit(arr_to_split,2)
split_vertical[0]
split_vertical[1]

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

# Part 3: Indexing, Slicing, and Boolean Indexing

##### 1. Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [36]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
print(data[1,2])

15


##### 2. From the data array (from Q13), extract the first two rows and all columns.

In [37]:
print(data[:2, :])

[[10 11 12]
 [13 14 15]]


##### 3. From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [38]:
row = [0,1,2]
col = [1,2,1]
data[row,col]

array([11, 15, 17])

##### 4. Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [39]:
scores = np.array([85, 92, 78, 65, 95, 88])
high_scores = scores[scores > 80]
high_scores

array([85, 92, 95, 88])

# Part 4: Numerical Operations and Aggregations

##### 1. Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [40]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
product  = arr_op1 * arr_op2
quotient = arr_op1 / arr_op2
print("Multiply:",  product)   
print("Divide:  ", quotient)

Multiply: [ 20  80 180]
Divide:   [5. 5. 5.]


##### 2. Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [41]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix_sum = np.sum(matrix)
print(matrix_sum)

45


##### 3. From the matrix (from Q18), calculate the mean of each column.

In [42]:
matrix_column_mean = np.mean(matrix, axis = 0)
matrix_column_mean

array([4., 5., 6.])

##### 4. Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [43]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discounted_prices = price_array * (1 - discount_percentage)
print("Discounted prices:", discounted_prices)

Discounted prices: [ 90. 135. 180. 225.]
