In [ ]:
# part 1


In [15]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6]).reshape(2, 3)
print(arr)

[[1 2 3]
 [4 5 6]]


In [8]:
arr2d= np.arange(1, 11).reshape(2,5)
print(arr2d)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [9]:
arr2d= np.arange(1, 10).reshape(3, 3)
print(arr2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


task 4


In [19]:
random_matrix=np.random.rand(6, 3)
print(random_matrix)

[[0.85296322 0.22053623 0.94830167]
 [0.63370611 0.47262909 0.34225773]
 [0.30947451 0.59439788 0.9811631 ]
 [0.62025029 0.41352196 0.7552287 ]
 [0.12007806 0.85040033 0.26109352]
 [0.83598351 0.8919796  0.35499186]]


In [21]:
linspace_array= np.linspace(0, 1, 7)
print(linspace_array)


[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


In [23]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("shape:", arr.shape)
print("ndim:", arr.ndim)
print("dtype:", arr.dtype)

shape: (2, 3)
ndim: 2
dtype: int64


In [29]:
arr1d= np.array([1, 2, 3, 4]).reshape(2, 2)
print(arr1d)

[[1 2]
 [3 4]]


In [32]:
import pandas as pd
my_list=([1, 2, 3, 4])
s = pd.Series(my_list)
s

0    1
1    2
2    3
3    4
dtype: int64

In [34]:
data={
    "name":["mahmood","adham", "salim" ],
    "age": [23, 25, 35], 
    "city": ["sinaw", "seeb", "muscat"]
}
df =pd.DataFrame(data)
df

name  age    city
0  mahmood   23   sinaw
1    adham   25    seeb
2    salim   35  muscat

In [42]:
np_arr =np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
df_np = pd.DataFrame(np_arr, index= ["Raw1", "Raw2", "Raw3"], columns =["col_1", "col_2", "col_3"])
df_np

col_1  col_2  col_3
Raw1      1      2      3
Raw2      4      5      6
Raw3      7      8      9

In [37]:
df_np.col_3

Raw1    3
Raw2    6
Raw3    9
Name: col_3, dtype: int64

In [54]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]).reshape(3,3)
print(data)
extract_data = data[1, 2]
print(extract_data)

[[10 11 12]
 [13 14 15]
 [16 17 18]]
15


In [77]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]).reshape(3,3)

extract_data = data[0:2, :]
print(extract_data)

[[10 11 12]
 [13 14 15]]


In [82]:

print(data[0, 1],data[1, 2],data[2, 1])


11 15 17


# task_3 num 5

In [89]:
scores = np.array([85, 92, 78, 65, 95, 88])
boolean= scores >80
print(boolean)
greater_than_80= scores[boolean]
print(greater_than_80)

[ True  True False False  True  True]
[85 92 95 88]


Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [94]:
arr_op1 = np.array([10, 20, 30])  
arr_op2 = np.array([2, 4, 6])
multiplication= arr_op1 * arr_op2
print(multiplication)
division=(arr_op1 / arr_op2)
print(division)

[ 20  80 180]
[5. 5. 5.]


Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [104]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
sumation =np.sum(matrix)
print(sumation)

45


From the matrix (from Q18), calculate the mean of each column.

In [106]:
mean_matrix = np.mean(matrix)
print(mean_matrix)

5.0


Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [108]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.90 * price_array
print(discount_percentage)

[ 90. 135. 180. 225.]
