In [2]:
import numpy as np



##part one

In [7]:
arr1d = np.arange(10)
print("Q1. arr1d:", arr1d, "\n")

Q1. arr1d: [0 1 2 3 4 5 6 7 8 9] 



In [8]:
# Q2.
arr2d = np.ones((3, 3))
print("Q2. arr2d:\n", arr2d, "\n")

Q2. arr2d:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]] 



In [9]:
#Q3. 
random_matrix = np.random.randn(3, 3)
print("Q3. random_matrix:\n", random_matrix, "\n")

Q3. random_matrix:
 [[ 0.60203473  0.25907698 -0.54485437]
 [-0.46088874  0.13903137 -0.49842582]
 [ 0.90027891  1.8415427   0.58871068]] 



In [10]:
# Q4.
even_numbers = np.arange(10, 51, 2)
print("Q4. even_numbers:", even_numbers, "\n")


Q4. even_numbers: [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50] 



In [11]:
# Q5..
linspace_array = np.linspace(0, 1, 7)
print("Q5. linspace_array:", linspace_array, "\n")

Q5. linspace_array: [0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ] 



In [13]:
#Q6. 
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Q6. arr shape:", arr.shape)
print("Q6. arr ndim:", arr.ndim)
print("Q6. arr dtype:", arr.dtype, "\n")


Q6. arr shape: (2, 3)
Q6. arr ndim: 2
Q6. arr dtype: int64 



##part two

In [14]:
#Q7
reshaped_arr = arr1d.reshape(2, 5)
print("Q7. reshaped_arr:\n", reshaped_arr, "\n")


Q7. reshaped_arr:
 [[0 1 2 3 4]
 [5 6 7 8 9]] 



In [15]:
# Q8. 
transposed_arr = reshaped_arr.T
print("Q8. transposed_arr:\n", transposed_arr, "\n")


Q8. transposed_arr:
 [[0 5]
 [1 6]
 [2 7]
 [3 8]
 [4 9]] 



In [16]:
# Q9.
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
stacked_v = np.vstack((a, b))
print("Q9. stacked_v:\n", stacked_v, "\n")


Q9. stacked_v:
 [[1 2 3]
 [4 5 6]] 



In [17]:
#Q10. 
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
stacked_h = np.hstack((m1, m2))
print("Q10. stacked_h:\n", stacked_h, "\n")


Q10. stacked_h:
 [[1 2 5 6]
 [3 4 7 8]] 



In [18]:
#Q11. 
arr_to_split = np.arange(16).reshape(4, 4)
split_h = np.hsplit(arr_to_split, 2)
print("Q11. split_h parts:")
for i, part in enumerate(split_h, start=1):
    print(f"Part {i}:\n{part}\n")

Q11. split_h parts:
Part 1:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]

Part 2:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]



In [20]:
# Q12.
split_v = np.vsplit(arr_to_split, 2)

print("Q12. split_v parts:")
for i, part in enumerate(split_v, start=1):
    print(f"Part {i}:\n{part}\n")


Q12. split_v parts:
Part 1:
[[0 1 2 3]
 [4 5 6 7]]

Part 2:
[[ 8  9 10 11]
 [12 13 14 15]]



##part three

In [3]:
#Q13
data = np.array([[10, 11, 12],
                 [13, 14, 15],
                 [16, 17, 18]])
element = data[1, 2]
print("Q13. element at row 1, column 2:", element, "\n")

Q13. element at row 1, column 2: 15 



In [5]:
 #Q14. 
rows = data[:2, :]
print("Q14. first two rows:\n", rows, "\n")




Q14. first two rows:
 [[10 11 12]
 [13 14 15]] 



In [4]:
# Q15. 
elements = data[[0, 1, 2], [1, 2, 1]]
print("Q15. elements:", elements, "\n")

Q15. elements: [11 15 17] 



In [6]:
#Q16
scores = np.array([85, 92, 78, 65, 95, 88])
filtered = scores[scores > 80]
print("Q16. scores > 80:", filtered, "\n")

Q16. scores > 80: [85 92 95 88] 



part 4

In [7]:
 #Q17. 
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
mul = arr_op1 * arr_op2
div = arr_op1 / arr_op2
print("Q17. multiplication:", mul)
print("Q17. division:", div, "\n")



Q17. multiplication: [ 20  80 180]
Q17. division: [5. 5. 5.] 



In [8]:
# Q18
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
total_sum = matrix.sum()
print("Q18. total sum:", total_sum, "\n")

Q18. total sum: 45 



In [10]:
# Q19. 
mean_cols = matrix.mean(axis=0)
print("Q19. mean of each column:", mean_cols, "\n")



Q19. mean of each column: [4. 5. 6.] 



In [11]:


# Q20.
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
discounted_prices = price_array * (1 - discount_percentage)
print("Q20. discounted_prices:", discounted_prices, "\n")

Q20. discounted_prices: [ 90. 135. 180. 225.] 

