In [2]:
import numpy as np

## Part 1: Array Creation and Properties

#### Create a 1D array named arr1d with integers from 0 to 9.

In [3]:
arr1d = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr1d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### Create a 2D array named arr2d with shape (3, 3) filled with ones.

In [4]:
arr2d = np.ones((1,3,3))
arr2d

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

#### Create a 3x3 array named random_matrix with random floating-point numbers from a standard normal distribution.

In [5]:
random_matrix = np.random.randint(1,10,5 )
random_matrix

array([3, 3, 8, 4, 2], dtype=int32)

#### Create an array named even_numbers containing even numbers from 10 to 50 (inclusive).

In [6]:
even_numbers = np.arange(10, 51)
even_numbers[0::2]

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### Create an array named linspace_array containing 7 equally spaced numbers between 0 and 1 (inclusive).

In [7]:
linspace_array = np.linspace(0,1,7)
linspace_array

array([0.        , 0.16666667, 0.33333333, 0.5       , 0.66666667,
       0.83333333, 1.        ])

#### Given arr = np.array([[1, 2, 3], [4, 5, 6]]), what is its shape, ndim, and dtype? Print them.

In [8]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape)
print(arr.ndim)
print(arr.dtype)

(2, 3)
2
int64


## Part 2: Array Manipulation

#### Reshape arr1d (from Q1) into a 2x5 2D array. Name the new array reshaped_arr.

In [9]:
reshaped_arr = arr1d.reshape(2, 5)
reshaped_arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

#### Transpose reshaped_arr (from Q7). Name the result transposed_arr.

In [10]:
transposed_arr = np.transpose(reshaped_arr)
transposed_arr

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

#### Stack two 1D arrays a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]) vertically.

In [11]:
a = np.array([[1, 2, 3]])
b = np.array([[4, 5, 6]])
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

#### Stack two 2D arrays m1 = np.array([[1, 2], [3, 4]]) and m2 = np.array([[5, 6], [7, 8]]) horizontally.

In [12]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([[5, 6], [7, 8]])
np.hstack((m1, m2))

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### Split the array arr_to_split = np.arange(16).reshape(4, 4) horizontally into 2 equal parts. Print both parts.

In [13]:
arr_to_split = np.arange(16).reshape(4, 4)
np.hsplit(arr_to_split, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

#### Split the array arr_to_split (from Q11) vertically at index 2 (i.e., into two parts: first two rows, and last two rows). Print both parts.

In [14]:
np.vsplit(arr_to_split, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

## Part 3: Indexing, Slicing, and Boolean Indexing

#### Given data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]]), extract the element at row 1, column 2.

In [18]:
data = np.array([[10, 11, 12], [13, 14, 15], [16, 17, 18]])
data[0, 1]

np.int64(11)

#### From the data array (from Q13), extract the first two rows and all columns.

In [22]:
data[:2]

array([[10, 11, 12],
       [13, 14, 15]])

#### From the data array (from Q13), extract the elements 11, 15, and 17 using fancy indexing (hint: you'll need to specify rows and columns).

In [43]:
print(data[0,1], data[1,2], data[2,1])

11 15 17


#### Given scores = np.array([85, 92, 78, 65, 95, 88]), use boolean indexing to find all scores greater than 80.

In [26]:
scores = np.array([85, 92, 78, 65, 95, 88])
s = scores > 80
s

array([ True,  True, False, False,  True,  True])

## Part 4: Numerical Operations and Aggregations

#### Given arr_op1 = np.array([10, 20, 30]) and arr_op2 = np.array([2, 4, 6]), perform element-wise multiplication and division (arr_op1 / arr_op2).

In [28]:
arr_op1 = np.array([10, 20, 30])
arr_op2 = np.array([2, 4, 6])
print(arr_op1 * arr_op2)
print(arr_op1 / arr_op2)

[ 20  80 180]
[5. 5. 5.]


#### Given matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]), calculate the sum of all elements in the matrix.

In [33]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matrix.sum()

np.int64(45)

#### From the matrix (from Q18), calculate the mean of each column.

In [35]:
matrix.mean()

np.float64(5.0)

#### Given price_array = np.array([100, 150, 200, 250]) and discount_percentage = 0.10, apply a 10% discount to all prices using broadcasting.

In [40]:
price_array = np.array([100, 150, 200, 250])
discount_percentage = 0.10
p = price_array * discount_percentage
a = price_array - p
a

array([ 90., 135., 180., 225.])