#### Sales Data Simulation and Analysis

In [2]:
import numpy as np

##### Sales Data Generation: 

##### Simulate daily sales_revenue for 30 days. Assume a base daily revenue (e.g., $1000) with random fluctuations. Use np.random.rand() or np.random.normal() to add variability. Ensure no negative sales.
 
##### Simulate units_sold for the same 30 days, correlated with sales revenue but with its own random fluctuations.
 
##### Create two 1D NumPy arrays, one for sales_revenue and one for units_sold.

In [7]:
sales_revenue = np.random.normal(loc = 1000,scale = 200 , size = 30)
sales_revenues = np.array(sales_revenue)
sales_revenues

array([1204.03777453, 1102.19664777,  905.56261997, 1192.01761041,
        975.00136279,  851.76658587,  965.24038239, 1067.31132435,
       1097.33469039, 1238.59374691, 1101.38319161, 1069.9099526 ,
        794.64676826, 1106.03074802, 1160.94811845,  883.92922724,
        553.22600584, 1076.43612207, 1143.00089802,  776.38091513,
       1018.4185687 ,  544.59843245,  671.84404507, 1194.85657527,
       1055.09788127,  789.8285745 ,  988.26632084,  634.62775344,
        671.62492632, 1207.10180162])

In [8]:
units_sold = sales_revenues / 10 + np.random.normal(loc=0, scale=5, size=30) #assume each product for 10$
unit_sold = np.round(units_sold).astype(int)
unit_sold

array([120, 105,  95, 118,  96,  81,  99, 102, 114, 115, 113, 105,  78,
       112, 113,  91,  60, 107, 110,  78, 105,  51,  64, 121, 111,  85,
        98,  68,  66, 136])

##### Combine Data: 


##### Create a 2D NumPy array where the first column is sales_revenue and the second is units_sold.

In [21]:
new_arr = np.vstack( [sales_revenues , unit_sold]).T
new_arr

array([[1204.03777453,  120.        ],
       [1102.19664777,  105.        ],
       [ 905.56261997,   95.        ],
       [1192.01761041,  118.        ],
       [ 975.00136279,   96.        ],
       [ 851.76658587,   81.        ],
       [ 965.24038239,   99.        ],
       [1067.31132435,  102.        ],
       [1097.33469039,  114.        ],
       [1238.59374691,  115.        ],
       [1101.38319161,  113.        ],
       [1069.9099526 ,  105.        ],
       [ 794.64676826,   78.        ],
       [1106.03074802,  112.        ],
       [1160.94811845,  113.        ],
       [ 883.92922724,   91.        ],
       [ 553.22600584,   60.        ],
       [1076.43612207,  107.        ],
       [1143.00089802,  110.        ],
       [ 776.38091513,   78.        ],
       [1018.4185687 ,  105.        ],
       [ 544.59843245,   51.        ],
       [ 671.84404507,   64.        ],
       [1194.85657527,  121.        ],
       [1055.09788127,  111.        ],
       [ 789.8285745 ,   

##### Key Performance Indicators (KPIs):


###### Calculate the total sales_revenue for the month.

In [23]:
total_revenue = np.sum(sales_revenues)
total_revenue

np.float64(29041.21957211945)

###### Calculate the average units_sold per day.

In [34]:
average_units_sold = np.mean(unit_sold)
average_units_sold

np.float64(97.23333333333333)

###### Determine the maximum daily sales_revenue and the day (index) it occurred.

In [31]:
max_sales_revenue = np.max(sales_revenues)
print(max_sales_revenue)
max_day = np.where(sales_revenue == np.max(sales_revenue)) [0][0] # to specify the output we can use [0][0] out of pracets 
print(max_day)

1238.593746905844
9


###### Calculate the average revenue per unit sold for the entire month (total revenue / total units sold).

In [42]:
average_revenue_per_unit_sold = total_revenue / (np.sum(unit_sold))
average_revenue_per_unit_sold

np.float64(9.95585175595456)

##### Conditional Analysis:

###### Identify and count how many days had sales_revenue above a certain target (e.g., $1200)

In [44]:
condition = sales_revenues > 900
count_sales = np.sum(condition)
count_sales 

np.int64(20)

###### Calculate the average units_sold only for days when sales_revenue was below a certain threshold (e.g., $900).

In [46]:
condition = sales_revenues < 900
average_unit_sold = np.mean(unit_sold[condition]) # use [] when try to spesify value that in other array
the_average = np.round(average_unit_sold) # using round up because we cant sale part of the product 
the_average

np.float64(72.0)

##### Weekly Aggregations: 

###### Assume the 30 days start on a Monday. Calculate the total sales_revenue for each of the 4 full weeks (days 1-7, 8-14, 15-21, 22-28). You will need to reshape or carefully slice your data.

In [61]:
week_day = sales_revenues[:28]
re_shape = week_day.reshape(4,7)
total_sales = np.sum(re_shape,axis = 1) #axis = 1 because the column have values for different weeks but row have all values for one week
total_sales

array([7195.82298373, 7475.21042213, 6612.33985546, 5879.11958285])